import json
from pathlib import Path
import subprocess
import tempfile

import common
import f32


APPEND = ("{% for message in messages %}"
          "{% if message['role'] == 'assistant' %}b{% endif %}"
          "{{ message['content'] }}{% endfor %}"
          "{% if add_generation_prompt %}b{% endif %}")
CASES = [
    {"name": "no-generation-suffix", "template": "{{ messages[-1]['content'] }}",
     "inputs": ["a", "ab", "abc"], "max_tokens": 1},
    {"name": "rewrite-longer", "template": "{{ messages[-1]['content'] }}",
     "inputs": ["a", "aaa"], "max_tokens": 1},
    {"name": "append", "template": APPEND,
     "inputs": ["a", "c", "d"], "max_tokens": 1},
    {"name": "token-limit", "template": APPEND,
     "inputs": ["a", "c"], "max_tokens": 2},
    {"name": "stop-before-feed", "template": APPEND,
     "inputs": ["a", "c", "d"], "max_tokens": 2, "stop": "J"},
    {"name": "eos", "template": "{{ messages[-1]['content'] }}",
     "inputs": ["a", "ab", "abc"], "max_tokens": 1, "eos_id": 205},
    {"name": "rewrite-and-shorten",
     "template": "{{ messages[-1]['content'] }}{% if add_generation_prompt %}b{% endif %}",
     "inputs": ["abc", "a", "c", "c"], "max_tokens": 1},
    {"name": "identical-prompt", "template": "ab",
     "inputs": ["a", "c"], "max_tokens": 1, "eos_id": 74},
    {"name": "elif-else-and-trailing-text",
     "template": "{% if messages[-1]['content'] == 'a' %}a"
                 "{% elif messages[-1]['content'] == 'b' %}ab{% else %}abc{% endif %}d",
     "inputs": ["a", "b", "c"], "max_tokens": 1},
]


def run():
    fixture = json.loads((Path(__file__).parent / "data/baseline_chat.json").read_text())
    weights = f32.tensors(False)
    assert fixture["weights_sha256"] == f32.weight_hash(weights)
    assert fixture["config"] == f32.CONFIG
    assert [case["spec"] for case in fixture["cases"]] == CASES
    with tempfile.TemporaryDirectory(prefix="llmx_chat_") as directory:
        model = Path(directory) / "chat.gguf"
        for case in fixture["cases"]:
            spec = case["spec"]
            f32.write_model(model, weights, spec["template"], spec.get("eos_id"))
            expected = b"".join(bytes(turn["reply_ids"]) + b"\n" for turn in case["turns"])
            for threads in (1, 4):
                for ubatch in (1, 3, 16):
                    args = [common.exe_path(), "chat", str(model), "--system", "",
                            "--temp", "0", "-n", str(spec["max_tokens"]),
                            "--threads", str(threads), "--ubatch", str(ubatch)]
                    if "stop" in spec:
                        args += ["--stop", spec["stop"]]
                    p = subprocess.run(args, input=("\n".join(spec["inputs"]) + "\n").encode(),
                                       capture_output=True, timeout=30)
                    assert p.returncode == 0, (spec["name"], p.returncode, p.stderr)
                    # Windows text-mode stdout translates line feeds, including
                    # any generated byte with that value.
                    output = p.stdout.replace(b"\r\n", b"\n")
                    banner = b"Chat ready (type your message; Ctrl+C to quit)\n"
                    assert output == banner + expected, (spec["name"], output, expected)
        f32.write_model(model, weights, "{% if false %}x{% endif %}")
        p = subprocess.run([common.exe_path(), "chat", str(model)], input=b"a\n",
                           capture_output=True, timeout=30)
        assert p.returncode == 1 and b"empty prompt" in p.stderr, (p.returncode, p.stderr)
    print("chat: follow-up replies vs HF; append, rewrite, reset, stop/EOS and token limit  [ok]")
    return True
