// The server's repair of generated bytes before they go into JSON: `utf8_complete` holds back a character split across tokens until its bytes arrive, and `utf8_sanitize` replaces each byte that starts no valid UTF-8 character with U+FFFD and keeps valid text unchanged.
#include <iostream>
#include <stdexcept>
#include <string>
#include "server/api.hpp"

namespace {
const std::string R = "\xEF\xBF\xBD";

void expect(const std::string& in, const std::string& want, const char* what) {
    if (server::utf8_sanitize(in) != want) throw std::runtime_error(what);
}

void expect_complete(const std::string& in, size_t want, const char* what) {
    if (server::utf8_complete(in) != want) throw std::runtime_error(what);
}
}

int main() {
    try {
        // A surrogate, an overlong form and a value above U+10FFFF, each well formed by its lead and continuation bytes alone.
        expect("\xED\xA0\x80", R + R + R, "surrogate U+D800 kept");
        expect("\xE0\x80\x80", R + R + R, "overlong U+0000 kept");
        expect("\xF4\x90\x80\x80", R + R + R + R, "U+110000 kept");
        expect("a\xED\xA0\x80" "b", "a" + R + R + R + "b", "surrogate between ASCII kept");
        // Truncated and stray bytes.
        expect("a\xE4\xB8" "b", "a" + R + R + "b", "truncated character kept");
        expect("\x80\xC0\xAF\xF5\xFF", R + R + R + R + R, "stray byte kept");
        // Valid text, with the first and last value of each length and on both sides of the surrogates.
        const std::string valid = "text \x7F \xC2\x80 \xDF\xBF \xE0\xA0\x80 \xED\x9F\xBF \xEE\x80\x80 \xEF\xBF\xBF "
                                  "\xF0\x90\x80\x80 \xF4\x8F\xBF\xBF \xE4\xB8\xAD\xF0\x9F\x98\x80";
        expect(valid, valid, "valid text changed");
        expect("", "", "empty text changed");
        // A character whose bytes have not all arrived is held back, and one that is whole goes out.
        expect_complete("a\xE4\xB8", 1, "split three-byte character let through");
        expect_complete("a\xE4", 1, "lone lead byte let through");
        expect_complete("\xF0\x9F\x98", 0, "split four-byte character let through");
        expect_complete("a\xE4\xB8\xAD", 4, "whole three-byte character held back");
        expect_complete("\xF0\x9F\x98\x80", 4, "whole four-byte character held back");
        // A continuation byte with no lead before it can never complete, so it is not held.
        expect_complete("a\x80", 2, "stray continuation byte held back");
        expect_complete("", 0, "empty text held back");
        std::cout << "server utf8: surrogate, overlong and out-of-range sequences replaced, valid text unchanged, split characters held back\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "server utf8: " << e.what() << '\n';
        return 1;
    }
}
