// The server's repair of generated bytes before they go into JSON: `utf8_complete` holds back a character split across tokens until its bytes arrive, and `utf8_sanitize` replaces each byte that starts no valid UTF-8 character with U+FFFD.
// `error_json` repairs an error message the same way, and `compat_number` writes a log-probability as a number wherever JSON has none.
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include "server/api.hpp"

namespace {
const std::string R = "\xEF\xBF\xBD";

void expect(const std::string& in, const std::string& want, const char* what) {
    if (server::utf8_sanitize(in) != want) throw std::runtime_error(what);
}

void expect_complete(const std::string& in, size_t want, const char* what) {
    if (server::utf8_complete(in) != want) throw std::runtime_error(what);
}
}

int main() {
    try {
        // A surrogate, an overlong form and a value above U+10FFFF, each well formed by its lead and continuation bytes alone.
        expect("\xED\xA0\x80", R + R + R, "surrogate U+D800 kept");
        expect("\xE0\x80\x80", R + R + R, "overlong U+0000 kept");
        expect("\xF4\x90\x80\x80", R + R + R + R, "U+110000 kept");
        expect("a\xED\xA0\x80" "b", "a" + R + R + R + "b", "surrogate between ASCII kept");
        // Truncated and stray bytes.
        expect("a\xE4\xB8" "b", "a" + R + R + "b", "truncated character kept");
        expect("\x80\xC0\xAF\xF5\xFF", R + R + R + R + R, "stray byte kept");
        // Valid text, with the first and last value of each length and on both sides of the surrogates.
        const std::string valid = "text \x7F \xC2\x80 \xDF\xBF \xE0\xA0\x80 \xED\x9F\xBF \xEE\x80\x80 \xEF\xBF\xBF "
                                  "\xF0\x90\x80\x80 \xF4\x8F\xBF\xBF \xE4\xB8\xAD\xF0\x9F\x98\x80";
        expect(valid, valid, "valid text changed");
        expect("", "", "empty text changed");
        // A character whose bytes have not all arrived is held back, and one that is whole goes out.
        expect_complete("a\xE4\xB8", 1, "split three-byte character let through");
        expect_complete("a\xE4", 1, "lone lead byte let through");
        expect_complete("\xF0\x9F\x98", 0, "split four-byte character let through");
        expect_complete("a\xE4\xB8\xAD", 4, "whole three-byte character held back");
        expect_complete("\xF0\x9F\x98\x80", 4, "whole four-byte character held back");
        // A continuation byte with no lead before it can never complete, so it is not held.
        expect_complete("a\x80", 2, "stray continuation byte held back");
        expect_complete("", 0, "empty text held back");
        // An error message can carry bytes from outside the request, a chat template's from the model file among them, and goes out repaired in either shape.
        const std::string message = "chat template: unbalanced {% if \xFF %}";
        const std::string repaired = "chat template: unbalanced {% if " + R + " %}";
        if (server::error_json(message, false) != "{\"error\":\"" + repaired + "\"}")
            throw std::runtime_error("native error message kept a stray byte");
        if (server::error_json(message, true) != "{\"error\":{\"message\":\"" + repaired + "\",\"type\":\"invalid_request_error\"}}")
            throw std::runtime_error("compatible error message kept a stray byte");
        // The compatible shapes type a log-probability as a number, so one below -9999, minus infinity and a NaN are written as -9999, where the native shapes' writer gives null for the last two.
        const float inf = std::numeric_limits<float>::infinity(), none = std::numeric_limits<float>::quiet_NaN();
        if (server::compat_number(-0.25f) != "-0.25" || server::compat_number(-9999.0f) != "-9999" || server::compat_number(-10000.0f) != "-9999" ||
            server::compat_number(-3.0e38f) != "-9999" || server::compat_number(-inf) != "-9999" || server::compat_number(none) != "-9999")
            throw std::runtime_error("a compatible log-probability not floored at -9999");
        if (jmini::number(-inf) != "null" || jmini::number(none) != "null") throw std::runtime_error("a native log-probability JSON cannot hold not written as null");
        // A reply is read again as its client sends it back: the compatible route's as its content alone, whatever reasoning came before it, the native route's whole.
        const chat::ChatFormat keeps = chat::chat_format("{% for m in messages %}|{{ m.role }}:{% if m.reasoning_content is defined %}<{{ m.reasoning_content }}>{% endif %}{{ m.content }}{% endfor %}"
                                                         "{% if add_generation_prompt %}|assistant:<think>\n{% endif %}", "", "");
        const std::string reply = "why\n</think>\n\nanswer";
        const chat::Message compatible = server::reply_sent_back(keeps, true, true, reply), native = server::reply_sent_back(keeps, false, true, reply);
        if (compatible.content != "answer" || compatible.reasoning_content) throw std::runtime_error("a compatible chat reply read again with the reasoning its client does not send back");
        if (keeps.render({{"user", "q", std::nullopt}, compatible, {"user", "r", std::nullopt}}, false) != "|user:q|assistant:answer|user:r")
            throw std::runtime_error("a compatible chat reply read again as another prompt than its content sent back renders");
        if (native.content != keeps.assistant(reply).content || native.reasoning_content != keeps.assistant(reply).reasoning_content) throw std::runtime_error("a native chat reply not read again as the format keeps a turn");
        std::cout << "server utf8: surrogate, overlong and out-of-range sequences replaced, valid text unchanged, split characters held back, "
                     "error messages repaired, compatible log-probabilities floored, a reply read again as its client sends it back\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "server utf8: " << e.what() << '\n';
        return 1;
    }
}
