"""Calibrate the tiny-fixture error budget of each 16-bit activation dtype (docs/PRECISION.md).

A dtype class's budget is what the class itself costs against HF in float32: the same HF model, its weights exact, the input of every matrix product rounded to the dtype and the sums in float32, over the tiny fixtures of tests/f32.py, tests/moe.py and tests/mxfp4.py at their own weights and at further seeds.
A router keeps float32 inputs by its operation role; weight storage does not select activation precision.
The largest error of each class, times MARGIN, is its frozen budget; integrating tests/common.py with actual execution witnesses is a separate step.
Run once in the HF reference environment of tools/gen_baseline.py, then commit tests/data/dtype_budget.json, before any candidate path is measured against it.

    python tools/calibrate_dtype.py --output FILE
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tests"))
sys.path.insert(0, HERE)

SEEDS = (0, 1, 2, 3)      # further weights beside each fixture's own
MARGIN = 2.0              # budget over the largest error measured
DTYPES = ("f16", "bf16")


def rounding(model, torch, dtype):
    """Hooks rounding each matrix product's input to `dtype`, routers excepted; returns the handles."""
    target = {"f16": torch.float16, "bf16": torch.bfloat16}[dtype]
    handles = []
    for name, module in model.named_modules():
        if isinstance(module, torch.nn.Linear) and not name.endswith("mlp.gate"):
            handles.append(module.register_forward_pre_hook(lambda _, args: (args[0].to(target).to(torch.float32),) + args[1:]))
    return handles


def errors(model, torch, dtype):
    """The largest full-vocabulary logit error and windowed NLL error of `dtype` against float32, over reference_outputs' texts."""
    from gen_baseline import reference_outputs
    cases, nll = reference_outputs(model, torch)
    handles = rounding(model, torch, dtype)
    try:
        rcases, rnll = reference_outputs(model, torch)
    finally:
        for h in handles:
            h.remove()
    logit = max(max(abs(a - b) for a, b in zip(c["logits"], r["logits"])) for c, r in zip(cases, rcases))
    return logit, max(abs(a["mean_nll"] - b["mean_nll"]) for a, b in zip(nll, rnll))


def models():
    """Each tiny fixture family at its own weights and at SEEDS: (name, seed, model, weights)."""
    from gen_baseline import tiny_moe, tiny_mxfp4, tiny_qwen3
    from mxfp4 import VARIANTS
    for tied in (False, True):
        for seed in (12345,) + SEEDS:
            model, weights = tiny_qwen3(tied, seed)
            yield "f32-%s" % ("tied" if tied else "untied"), seed, model, weights
    for seed in (67890,) + SEEDS:
        model, weights = tiny_moe(seed)
        yield "moe", seed, model, weights
    for name, tied, moe in VARIANTS:
        for seed in (12345,) + SEEDS:
            model, _, weights, _ = tiny_mxfp4(tied, moe, seed)
            yield "mxfp4-" + name, seed, model, weights


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--output", required=True, help="new result file; never overwrites a frozen budget")
    args = parser.parse_args(argv)
    import torch
    import transformers
    if torch.__version__ != "2.5.1+cpu" or transformers.__version__ != "4.55.2":
        raise SystemExit("calibration requires torch 2.5.1+cpu and transformers 4.55.2")
    torch.set_num_threads(1)
    runs = {d: [] for d in DTYPES}
    from f32 import weight_hash
    for name, seed, model, weights in models():
        for d in DTYPES:
            logit, nll = errors(model, torch, d)
            runs[d].append({"fixture": name, "seed": seed, "weights_sha256": weight_hash(weights), "logit_error": logit, "nll_error": nll})
            print("%-18s seed %-6d %-4s logit %.8f nll %.8f" % (name, seed, d, logit, nll))
    doc = {"_comment": "Generated by tools/calibrate_dtype.py: each 16-bit class against HF float32 on the tiny fixtures, weights exact, matrix-product inputs rounded, float32 sums.",
           "torch_version": torch.__version__, "transformers_version": transformers.__version__, "threads": torch.get_num_threads(), "margin": MARGIN, "dtypes": {}}
    for d in DTYPES:
        logit = max(r["logit_error"] for r in runs[d])
        nll = max(r["nll_error"] for r in runs[d])
        doc["dtypes"][d] = {"max_logit_error": logit, "max_nll_error": nll,
                            "logit_budget": logit * MARGIN, "nll_budget": nll * MARGIN, "runs": runs[d]}
    with open(args.output, "x", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, indent=1)
        f.write("\n")
    print("wrote %s" % args.output)


if __name__ == "__main__":
    main()
