"""The layered HF reference: HF's own Qwen3.5 modules run in the order of its full forward, one decoder layer's weights in memory at a time.

    python tools/gen_layered_reference.py goldens --repo Qwen/Qwen3.5-9B --revision SHA --gguf FILE.gguf --output-dir DIR [--gguf-repo REPO --gguf-revision SHA]
    python tools/gen_layered_reference.py equality --output FILE

From the 9B up, a qwen35 model's float32 forward does not fit host memory whole.
This runs the calls of transformers' Qwen3_5TextModel.forward in its order: the embedding, the model's own rotary embedding and masks, each decoder layer, the final norm and the head.
Each module's weights are read from the checkpoint's safetensors just before it runs, widened from bf16 to float32 as from_pretrained does, and released once it has run every input, so a run holds one layer, the embedding or the head at a time.
Every input runs alone, a batch of one, as the full forward runs it, so every logit is the full forward's bit for bit.

goldens writes baseline_tokenizer.json, baseline_logits.json and baseline_perplexity.json into --output-dir with the writers of tools/gen_baseline.py, from the checkpoint's own weights, as the Qwen3-8B goldens are made.
The GGUF labels them: they record its SHA-256, and its F32 tensors are compared with the checkpoint's under the converter's conventions (docs/QWEN35.md), which shows the file was converted from these weights and which V-head order it stores.
equality runs Qwen/Qwen3.5-0.8B at the qwen35 tokenizer golden's commit both ways, HF's full forward and the layered one, on every input the goldens take, and records the SHA-256 of each one's logits.
It exits nonzero unless every pair and every parameter is equal, and tests/reference_generator.py holds the committed record to that.

Both run offline from the HF cache, which must already hold the checkpoint at the commit given.
They need the qwen35 reference venv that docs/ASSETS.md lists, and refuse another transformers or torch version and an installed kernels package, so HF's torch fallbacks run.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import sys
import time
from types import SimpleNamespace

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_baseline as generator

TRANSFORMERS_VERSION = "5.17.0"
TORCH_VERSION = "2.5.1+cpu"
# The equality check's model is the one whose tokenizer the qwen35 tokenizer golden pins.
EQUALITY_REPO = generator.QWEN35_REPO
EQUALITY_REVISION = generator.QWEN35_REVISION
COMMENT = ("Generated by tools/gen_layered_reference.py goldens from the full-precision reference: HF's own decoder layers run one at a time, "
           "on the checkpoint's weights widened to float32, equal to its full forward. Do not hand-edit.")


def tiled_order(k_heads, v_heads):
    """The HF V head that each GGUF V head holds: the converter stores HF head h r + s as GGUF head s Hk + h, with r = Hv / Hk (docs/QWEN35.md, V heads in tiled order)."""
    r = v_heads // k_heads
    return [h * r + s for s in range(r) for h in range(k_heads)]


def reference_rows(tok):
    """Every token row the golden writers of tools/gen_baseline.py run, labelled, as [1, N] tensors: each logit prompt, the perplexity text whole, then each window of its cases."""
    rows = [("logits %d" % i, tok(text, add_special_tokens=False, return_tensors="pt").input_ids)
            for i, text in enumerate(generator.LOGIT_PROMPTS)]
    ids = tok(generator.ppl_text(), add_special_tokens=False, return_tensors="pt").input_ids
    rows.append(("perplexity", ids))
    for context, limit in generator.PPL_WINDOWS:
        rows += [("perplexity %d/%d [%d, %d)" % (context, limit, start, end), ids[:, start:end])
                 for start, end in generator.ppl_window_bounds(ids.shape[1], context, limit)]
    return rows


def row_labels(prompts, text_tokens):
    """The labels reference_rows gives for `prompts` logit prompts and a perplexity text of `text_tokens` tokens."""
    labels = ["logits %d" % i for i in range(prompts)] + ["perplexity"]
    for context, limit in generator.PPL_WINDOWS:
        labels += ["perplexity %d/%d [%d, %d)" % (context, limit, start, end)
                   for start, end in generator.ppl_window_bounds(text_tokens, context, limit)]
    return labels


def runtime(threads):
    """torch and transformers, offline, on `threads` CPU threads, refused unless they are the reference's versions and no kernels package can replace HF's torch code."""
    os.environ["HF_HUB_OFFLINE"] = "1"
    if importlib.util.find_spec("kernels") is not None:
        raise SystemExit("the kernels package is installed, so HF could run hub kernels in place of its torch fallbacks")
    import torch
    import transformers
    if (transformers.__version__, torch.__version__) != (TRANSFORMERS_VERSION, TORCH_VERSION):
        raise SystemExit("the layered reference runs on transformers %s and torch %s, not %s and %s"
                         % (TRANSFORMERS_VERSION, TORCH_VERSION, transformers.__version__, torch.__version__))
    torch.set_num_threads(threads)
    return torch, transformers


def snapshot(repo, revision):
    """The HF cache's directory for the checkpoint at `revision`, which holds the files the cache has of it."""
    from huggingface_hub import hf_hub_download
    return os.path.dirname(hf_hub_download(repo, "config.json", revision=revision))


def checkpoint_plan(directory, model):
    """Where each parameter of `model` is stored in the checkpoint in `directory`, {name: (file, key)}, with the checkpoint keys the model does not take.
    Keys are renamed by transformers' own loading rules for the model, and a rule that would reshape a tensor, a key the model does not ignore, and a parameter no key gives other than a tied head are refused."""
    from safetensors import safe_open
    from transformers.conversion_mapping import get_model_conversion_mapping
    from transformers.core_model_loading import WeightConverter, WeightRenaming, rename_source_key

    index = os.path.join(directory, "model.safetensors.index.json")
    if os.path.exists(index):
        with open(index, encoding="utf-8") as f:
            stored = json.load(f)["weight_map"]
    else:
        with safe_open(os.path.join(directory, "model.safetensors"), framework="pt") as f:
            stored = {key: "model.safetensors" for key in f.keys()}
    mapping = get_model_conversion_mapping(model)
    renamings = [t for t in mapping if isinstance(t, WeightRenaming)]
    converters = [t for t in mapping if isinstance(t, WeightConverter)]
    meta = model.state_dict()
    prefix = model.base_model_prefix
    plan, unexpected = {}, []
    # As transformers' loader renames them: every renaming, then at most one converter, then the base model's prefix.
    for key in sorted(stored):
        name, converter = rename_source_key(key, renamings, converters, prefix, meta)
        if name not in meta and key in meta:
            name, converter = rename_source_key(key, [], [], prefix, meta)
        if name not in meta:
            unexpected.append(key)
            continue
        if converter is not None:
            raise SystemExit("%s: transformers converts %s on load, and the layered reference reads tensors as stored" % (directory, key))
        if name in plan:
            raise SystemExit("%s: %s and %s both give %s" % (directory, plan[name][1], key, name))
        plan[name] = (stored[key], key)
    ignored = [re.compile(pattern) for pattern in model._keys_to_ignore_on_load_unexpected]
    stray = [key for key in unexpected if not any(pattern.search(key) for pattern in ignored)]
    if stray:
        raise SystemExit("%s: %d checkpoint keys the model neither takes nor ignores, such as %s" % (directory, len(stray), stray[0]))
    tied = {"lm_head.weight"} if model.config.tie_word_embeddings else set()
    missing = set(meta) - set(plan) - tied
    if missing:
        raise SystemExit("%s: no checkpoint key gives %s" % (directory, ", ".join(sorted(missing))))
    return plan, unexpected


class Layered:
    """HF's Qwen3_5ForCausalLM for the checkpoint in `directory`, built on the meta device, whose modules hold weights only while they run.
    run() computes the logits of a list of token rows; calling it as a model, model(ids, use_cache=False), returns the logits run() computed for those ids."""

    def __init__(self, torch, directory):
        from transformers import Qwen3_5ForCausalLM, Qwen3_5TextConfig
        from transformers.models.qwen3_5.modeling_qwen3_5 import Qwen3_5TextRotaryEmbedding
        self.torch = torch
        self.directory = directory
        config = Qwen3_5TextConfig.from_pretrained(directory)
        config._attn_implementation = "eager"
        with torch.device("meta"):
            self.model = Qwen3_5ForCausalLM(config)
        self.model.eval().requires_grad_(False)
        if self.model.config._attn_implementation != "eager":
            raise SystemExit("the model runs %s attention, not eager" % self.model.config._attn_implementation)
        # The inverse frequencies are a buffer computed at construction, which the meta device leaves without values.
        self.rotary = Qwen3_5TextRotaryEmbedding(config=self.model.model.config)
        self.plan, self.unexpected = checkpoint_plan(directory, self.model)
        self.logits = {}

    def source(self, name):
        """The checkpoint parameter that gives the model's parameter `name`: a tied head reads the embedding."""
        return "model.embed_tokens.weight" if name == "lm_head.weight" and self.model.config.tie_word_embeddings else name

    def read(self, names):
        """The model's parameters `names` as the checkpoint stores them, widened to float32 as from_pretrained does.
        Each file is mapped only while its tensors are copied out, so no page of it stays resident after."""
        from safetensors import safe_open
        where = {name: self.plan[self.source(name)] for name in names}
        tensors = {}
        for file in sorted({file for file, _ in where.values()}):
            with safe_open(os.path.join(self.directory, file), framework="pt", device="cpu") as reader:
                for name, (source, key) in where.items():
                    if source == file:
                        tensors[name] = reader.get_tensor(key).to(dtype=self.torch.float32, copy=True)
        return tensors

    def load(self, module, prefix):
        """Give `module`, named `prefix` in the model, its parameters from the checkpoint."""
        state = self.read([prefix + name for name, _ in module.named_parameters()])
        module.load_state_dict({name[len(prefix):]: value for name, value in state.items()}, strict=True, assign=True)
        if any(t.is_meta for t in list(module.parameters()) + list(module.buffers())):
            raise SystemExit("%s holds a tensor the checkpoint does not give" % prefix)

    def release(self, module):
        module.to("meta")

    def run(self, rows, on_layer=None):
        """The logits at every position of each [1, N] row in `rows` that has none yet, computed layer by layer; `on_layer(name, module)` sees each decoder layer and the final norm while their weights are loaded."""
        from transformers.masking_utils import create_causal_mask, create_recurrent_attention_mask
        torch = self.torch
        text, config = self.model.model, self.model.model.config
        todo = {}
        for ids in rows:
            todo.setdefault(tuple(ids[0].tolist()), ids)
        todo = [(key, ids) for key, ids in todo.items() if key not in self.logits]
        states = []
        with torch.inference_mode():
            # Qwen3_5TextModel.forward with no cache and no attention mask, from its embedding to its first layer; with no cache, no token has been seen before the row.
            self.load(text.embed_tokens, "model.embed_tokens.")
            for _, ids in todo:
                embeds = text.embed_tokens(ids)
                position_ids = torch.arange(embeds.shape[1], device=embeds.device) + 0
                position_ids = position_ids.view(1, 1, -1).expand(4, embeds.shape[0], -1)
                text_position_ids, position_ids = position_ids[0], position_ids[1:]
                mask_kwargs = {"config": config, "inputs_embeds": embeds, "attention_mask": None,
                               "past_key_values": None, "position_ids": text_position_ids}
                masks = {"full_attention": create_causal_mask(**mask_kwargs),
                         "linear_attention": create_recurrent_attention_mask(**mask_kwargs)}
                states.append({"hidden": embeds, "rope": self.rotary(embeds, position_ids),
                               "masks": masks, "positions": text_position_ids})
            self.release(text.embed_tokens)
            for index, layer in enumerate(text.layers[: config.num_hidden_layers]):
                self.load(layer, "model.layers.%d." % index)
                if on_layer:
                    on_layer("model.layers.%d" % index, layer)
                for state in states:
                    state["hidden"] = layer(state["hidden"], position_embeddings=state["rope"],
                                            attention_mask=state["masks"][config.layer_types[index]],
                                            position_ids=state["positions"], past_key_values=None, use_cache=False)
                self.release(layer)
            # The final norm, then Qwen3_5ForCausalLM's head over every position.
            self.load(text.norm, "model.norm.")
            self.load(self.model.lm_head, "lm_head.")
            if on_layer:
                on_layer("model.norm", text.norm)
            for (key, _), state in zip(todo, states):
                hidden = text.norm(state["hidden"])
                self.logits[key] = self.model.lm_head(hidden[:, slice(0, None), :])
            self.release(text.norm)
            self.release(self.model.lm_head)

    def __call__(self, ids, use_cache=False):
        key = tuple(ids[0].tolist())
        if key not in self.logits:
            raise KeyError("the layered reference did not run this row of %d tokens" % len(key))
        return SimpleNamespace(logits=self.logits[key])


class Provenance:
    """A GGUF file's F32 tensors against the checkpoint's parameters under the converter's conventions (docs/QWEN35.md, What the converter folds).
    Every norm but ssm_norm is stored as 1 + w summed in float32, ssm_a as -exp(A_log), ssm_conv1d without its middle axis, and the V side in tiled order.
    ssm_dt.bias is also compared in HF's grouped order, which a file converted in tiled order with Hv above Hk must not match."""

    def __init__(self, path, config):
        import numpy
        import spec_decode
        self.np, self.spec = numpy, spec_decode
        self.gguf = spec_decode.GGUF(path)
        self.by_name = {t.name: t for t in self.gguf.tensors}
        self.k_heads, self.v_heads = config.linear_num_key_heads, config.linear_num_value_heads
        self.key_width = config.linear_num_key_heads * config.linear_key_head_dim
        self.tiled = numpy.array(tiled_order(self.k_heads, self.v_heads))
        self.equal, self.differ, self.linear_layers, self.grouped = 0, [], 0, 0

    def values(self, name):
        tensor = self.by_name[name]
        if tensor.type != self.spec.F32:
            raise SystemExit("%s is %s, not F32" % (name, self.spec.type_name(tensor.type)))
        return self.gguf.decode(tensor).reshape(list(reversed(tensor.shape)))

    def compare(self, name, expected):
        got = self.values(name)
        if got.shape == expected.shape and self.np.array_equal(got, expected):
            self.equal += 1
        else:
            self.differ.append(name)

    def __call__(self, name, module):
        np = self.np
        one = np.float32(1)

        def value(parameter):
            return parameter.detach().numpy()

        if name == "model.norm":
            self.compare("output_norm.weight", one + value(module.weight))
            return
        blk = "blk.%d." % int(name.rsplit(".", 1)[1])
        self.compare(blk + "attn_norm.weight", one + value(module.input_layernorm.weight))
        self.compare(blk + "post_attention_norm.weight", one + value(module.post_attention_layernorm.weight))
        if module.block_type == "linear_attention":
            mixer = module.linear_attn
            self.compare(blk + "ssm_dt.bias", value(mixer.dt_bias)[self.tiled])
            self.compare(blk + "ssm_a", (-mixer.A_log.exp()).numpy()[self.tiled])
            self.compare(blk + "ssm_norm.weight", value(mixer.norm.weight))
            conv = value(mixer.conv1d.weight)[:, 0, :]
            v = conv[2 * self.key_width:].reshape(self.v_heads, -1, conv.shape[1])[self.tiled].reshape(-1, conv.shape[1])
            self.compare(blk + "ssm_conv1d.weight", np.concatenate([conv[:2 * self.key_width], v]))
            self.grouped += int(np.array_equal(self.values(blk + "ssm_dt.bias"), value(mixer.dt_bias)))
            self.linear_layers += 1
        else:
            self.compare(blk + "attn_q_norm.weight", one + value(module.self_attn.q_norm.weight))
            self.compare(blk + "attn_k_norm.weight", one + value(module.self_attn.k_norm.weight))

    def record(self):
        return {"f32_tensors_compared": self.equal + len(self.differ), "equal": self.equal, "differ": self.differ,
                "v_heads": "%d V heads over %d K heads, compared in tiled order" % (self.v_heads, self.k_heads),
                "dt_bias_equal_in_grouped_order": "%d of %d linear-attention layers" % (self.grouped, self.linear_layers)}


def file_sha256(path):
    from baseline_8b import file_sha256 as digest
    return digest(Path(path))


def safetensors_sha256(directory):
    names = sorted(name for name in os.listdir(directory) if name.endswith(".safetensors"))
    with ThreadPoolExecutor(max_workers=4) as pool:
        return dict(zip(names, pool.map(lambda name: file_sha256(os.path.join(directory, name)), names)))


def check_tokenizer(tok, directory):
    """The ids the golden writers take from transformers' tokenizer must be those of the checkpoint's tokenizer.json, whose pretokenizer llmx follows."""
    from tokenizers import Tokenizer
    raw = Tokenizer.from_file(os.path.join(directory, "tokenizer.json"))
    for text in list(generator.LOGIT_PROMPTS) + [generator.ppl_text()]:
        ids = tok(text, add_special_tokens=False).input_ids
        if ids != raw.encode(text, add_special_tokens=False).ids:
            raise SystemExit("transformers' tokenizer and tokenizer.json give different ids for %r" % text[:40])


def peak_gib():
    import resource
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2 ** 20


def label_golden(path, extra):
    """Put this reference's comment on a golden the writers of tools/gen_baseline.py wrote, and the fields of `extra` it lacks after its GGUF's file name, or after the reference's metadata in a golden that names no GGUF."""
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    after = "gguf_file" if "gguf_file" in doc else "transformers_version"
    labelled = {}
    for key, value in doc.items():
        labelled[key] = COMMENT if key == "_comment" else value
        if key == after:
            labelled.update((k, v) for k, v in extra.items() if k not in doc)
    if not set(extra) <= set(labelled):
        raise SystemExit("%s has neither gguf_file nor transformers_version to label after" % path)
    generator._write(path, labelled)


def goldens(args):
    torch, transformers = runtime(args.threads)
    from transformers import AutoTokenizer
    directory = snapshot(args.repo, args.revision)
    start = time.time()
    checkpoint = safetensors_sha256(directory)
    gguf = {"gguf_repo": args.gguf_repo, "gguf_file": os.path.basename(args.gguf), "gguf_revision": args.gguf_revision,
            "gguf_sha256": file_sha256(args.gguf), "gguf_bytes": os.path.getsize(args.gguf)}
    print("hashed the checkpoint and the GGUF in %.1f s" % (time.time() - start), flush=True)
    tok = AutoTokenizer.from_pretrained(args.repo, revision=args.revision)
    rows = reference_rows(tok)
    check_tokenizer(tok, directory)
    layered = Layered(torch, directory)
    provenance = Provenance(args.gguf, layered.model.config)
    start = time.time()
    layered.run([ids for _, ids in rows], on_layer=provenance)
    print("layered forward: %d rows, %d distinct, %.1f s, peak RSS %.2f GiB"
          % (len(rows), len(layered.logits), time.time() - start, peak_gib()), flush=True)
    print("GGUF provenance: %s" % json.dumps(provenance.record()), flush=True)
    writer = SimpleNamespace(repo=args.repo, revision=args.revision, threads=args.threads, output_dir=args.output_dir,
                             gguf_repo=args.gguf_repo, gguf_file=os.path.basename(args.gguf), weights_gguf=None)
    os.makedirs(args.output_dir, exist_ok=True)
    generator.gen_tokenizer(writer)
    generator.gen_logits(writer, (torch, transformers, tok, layered))
    generator.gen_perplexity(writer, (torch, transformers, tok, layered))
    reference = {"layered": {
        "weights": "the checkpoint's own bf16 safetensors widened to float32, not the GGUF's",
        "safetensors_sha256": checkpoint,
        "unexpected_keys_ignored": len(layered.unexpected),
        "gguf_provenance": provenance.record()}}
    label_golden(os.path.join(args.output_dir, "baseline_tokenizer.json"), gguf)
    for name in ("baseline_logits.json", "baseline_perplexity.json"):
        label_golden(os.path.join(args.output_dir, name), dict(gguf, **reference))
    print("peak RSS %.2f GiB" % peak_gib(), flush=True)


def equality(args):
    torch, transformers = runtime(args.threads)
    from transformers import AutoTokenizer, Qwen3_5ForCausalLM
    directory = snapshot(EQUALITY_REPO, EQUALITY_REVISION)
    tok = AutoTokenizer.from_pretrained(EQUALITY_REPO, revision=EQUALITY_REVISION)
    rows = reference_rows(tok)
    check_tokenizer(tok, directory)
    layered = Layered(torch, directory)
    start = time.time()
    layered.run([ids for _, ids in rows])
    layered_seconds = time.time() - start
    full, info = Qwen3_5ForCausalLM.from_pretrained(EQUALITY_REPO, revision=EQUALITY_REVISION, dtype=torch.float32,
                                                    attn_implementation="eager", output_loading_info=True)
    full.eval()
    ignored = [re.compile(pattern) for pattern in full._keys_to_ignore_on_load_unexpected]
    if info["missing_keys"] or any(not any(p.search(k) for p in ignored) for k in info["unexpected_keys"]):
        raise SystemExit("from_pretrained misses %s or takes unexpected %s" % (sorted(info["missing_keys"]), sorted(info["unexpected_keys"])[:4]))
    state = full.state_dict()
    equal = 0
    for names in (list(state)[i:i + 64] for i in range(0, len(state), 64)):
        equal += sum(1 for name, value in layered.read(names).items() if torch.equal(state[name], value))
    cases, start = [], time.time()
    with torch.inference_mode():
        for label, ids in rows:
            logits = full(ids, use_cache=False).logits
            mine = layered(ids).logits
            same = logits.dtype == mine.dtype and logits.shape == mine.shape and torch.equal(logits, mine)
            cases.append({"label": label, "tokens": int(ids.shape[1]),
                          "full_sha256": hashlib.sha256(logits.contiguous().numpy().tobytes()).hexdigest(),
                          "layered_sha256": hashlib.sha256(mine.contiguous().numpy().tobytes()).hexdigest(),
                          "max_abs_difference": 0.0 if same else float((logits - mine).abs().max())})
            print("  %-34s %s" % (label, "equal" if same else "differs by %g" % cases[-1]["max_abs_difference"]), flush=True)
    full_seconds = time.time() - start
    record = {
        "_comment": "Written by tools/gen_layered_reference.py equality. Do not hand-edit.",
        "reference_repo": EQUALITY_REPO, "reference_revision": EQUALITY_REVISION,
        "reference_dtype": "float32", "attention": "eager", "device": "cpu", "threads": args.threads,
        "torch_version": torch.__version__, "transformers_version": transformers.__version__,
        "parameters": len(state), "parameters_equal": equal,
        "inv_freq_equal": bool(torch.equal(full.model.rotary_emb.inv_freq, layered.rotary.inv_freq)),
        "unexpected_keys_ignored": len(layered.unexpected),
        "cases": cases,
    }
    generator._write(args.output, record)
    same = all(c["full_sha256"] == c["layered_sha256"] for c in cases) and equal == len(state) and record["inv_freq_equal"]
    print("wrote %s: %d of %d rows and %d of %d parameters equal; layered %.1f s, full forward %.1f s, peak RSS %.2f GiB"
          % (args.output, sum(c["full_sha256"] == c["layered_sha256"] for c in cases), len(cases), equal, len(state),
             layered_seconds, full_seconds, peak_gib()), flush=True)
    return 0 if same else 1


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="The layered HF reference of a qwen35 model, run offline on the CPU in float32.")
    kinds = parser.add_subparsers(dest="kind", required=True)
    make = kinds.add_parser("goldens", help="write the tokenizer, logit and perplexity goldens for a GGUF from its HF checkpoint")
    make.add_argument("--repo", required=True, help="HF repository of the checkpoint")
    make.add_argument("--revision", required=True, help="full 40-character commit SHA of the checkpoint")
    make.add_argument("--gguf", required=True, help="the GGUF the goldens are for, which they record and whose F32 tensors are compared with the checkpoint's")
    make.add_argument("--gguf-repo", help="the Hub repository the GGUF comes from, when it is known")
    make.add_argument("--gguf-revision", help="that repository's full commit SHA")
    make.add_argument("--output-dir", required=True, help="directory for the three goldens")
    make.add_argument("--threads", type=int, default=6, help="CPU threads (default: 6)")
    check = kinds.add_parser("equality", help="check the layered forward against HF's full forward on Qwen3.5-0.8B")
    check.add_argument("--output", required=True, help="file for the equality record")
    check.add_argument("--threads", type=int, default=6, help="CPU threads (default: 6)")
    args = parser.parse_args(argv)
    if args.threads < 1:
        parser.error("--threads must be positive")
    if args.kind == "goldens":
        if os.path.isdir(args.repo):
            parser.error("--repo must identify a Hub repository, not a local directory that bypasses revision pinning")
        for flag, value in (("--revision", args.revision), ("--gguf-revision", args.gguf_revision)):
            if value is not None and not re.fullmatch(r"[0-9a-f]{40}", value):
                parser.error("%s must be a full 40-character lowercase commit SHA" % flag)
        if args.gguf_revision and not args.gguf_repo:
            parser.error("--gguf-revision needs --gguf-repo")
        if not os.path.isfile(args.gguf):
            parser.error("--gguf %s is not a file" % args.gguf)
        args.output_dir = os.path.abspath(args.output_dir)
        if os.path.normcase(os.path.realpath(args.output_dir)) == os.path.normcase(os.path.realpath(generator.OUT_DIR)):
            parser.error("--output-dir cannot be the directory of the default fixtures")
    return args


def main(argv=None):
    args = parse_args(argv)
    if args.kind == "goldens":
        goldens(args)
        return 0
    return equality(args)


if __name__ == "__main__":
    sys.exit(main())
