"""Generate independent HF expectations for the tiny multi-turn chat fixtures.

Requires torch, transformers and Jinja2 only when regenerating this file.
The byte-only vocabulary maps each raw byte directly to its token ID; Latin-1
preserves generated bytes while the independent Jinja2 renderer formats turns.
"""
import argparse
import json
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def main():
    argparse.ArgumentParser(description="Regenerate tests/data/baseline_chat.json and baseline_chat_template.json "
                                        "from HF Qwen3ForCausalLM and Jinja2.").parse_args()
    # The packages are needed only to regenerate, as gen_baseline.py loads them, so --help runs without them.
    import jinja2
    from jinja2.sandbox import ImmutableSandboxedEnvironment
    import torch
    import transformers
    sys.path.insert(0, str(ROOT / "tests"))
    from chat import CASES
    from f32 import CONFIG, weight_hash
    from gen_baseline import tiny_qwen3

    torch.set_num_threads(1)
    model, weights = tiny_qwen3(False)
    cases = []
    with torch.inference_mode():
        for spec in CASES:
            messages = [{"role": "system", "content": ""}]
            template = jinja2.Template(spec["template"])
            turns = []
            for text in spec["inputs"]:
                messages.append({"role": "user", "content": text})
                prompt = list(template.render(messages=messages, add_generation_prompt=True)
                              .encode("latin-1"))
                assert prompt
                reply = []
                for _ in range(spec["max_tokens"]):
                    ids = prompt + reply
                    assert len(ids) < CONFIG["context_length"]
                    logits = model(torch.tensor([ids]), use_cache=False).logits[0, -1]
                    token = int(logits.argmax())
                    if token == spec.get("eos_id", 0):
                        break
                    assert token < 256, "fixture reply must use byte tokens"
                    reply.append(token)
                    if spec.get("stop") and spec["stop"].encode() in bytes(reply):
                        break
                turns.append({"prompt_ids": prompt, "reply_ids": reply})
                messages.append({"role": "assistant", "content": bytes(reply).decode("latin-1")})
            cases.append({"spec": spec, "turns": turns})
    result = {"source": "HF Qwen3ForCausalLM, full transcript recomputed each turn, Jinja2 rendering",
              "torch_version": torch.__version__, "transformers_version": transformers.__version__,
              "jinja2_version": jinja2.__version__, "dtype": "float32", "attention": "eager",
              "config": CONFIG, "weights_sha256": weight_hash(weights), "cases": cases}
    path = ROOT / "tests/data/baseline_chat.json"
    path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print("wrote", path)

    path = ROOT / "tests/data/baseline_chat_template.json"
    template = json.loads(path.read_text(encoding="utf-8"))["template"]
    environment = ImmutableSandboxedEnvironment(trim_blocks=True, lstrip_blocks=True)
    renderer = environment.from_string(template)
    messages = [{"role": "system", "content": "You are helpful."},
                {"role": "user", "content": "Remember violet."}]
    cases = []
    for turn in range(3):
        if turn:
            messages += [{"role": "assistant", "content":
                          "<think>Private reasoning.</think>\n\nViolet." if turn == 1 else "Violet again."},
                         {"role": "user", "content": "What color?" if turn == 1 else "Say it again."}]
        for complete in (False, True):
            history = messages + ([{"role": "assistant", "content": "<think>Reason.</think>\n\nAnswer."}]
                                  if complete else [])
            for generate in (False, True):
                expected = renderer.render(messages=history, add_generation_prompt=generate,
                                           bos_token="", eos_token="<|im_end|>")
                cases.append({"messages": history.copy(), "generate": generate, "expected": expected})
    result = {"source": "Qwen3-0.6B-Q8_0 GGUF snapshot 23749fefcc72300e3a2ad315e1317431b06b590a",
              "template_sha256": hashlib.sha256(template.encode()).hexdigest(),
              "jinja2_version": jinja2.__version__, "template": template, "cases": cases}
    path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print("wrote", path)


if __name__ == "__main__":
    main()
