"""Generate golden fixtures for the correctness baseline.

Run this ONCE on a machine that has the HF tooling, then commit the output.
tests/baseline.py only reads the committed JSON, so running the test suite
never needs torch, transformers, or network access -- llmx stays
dependency-free at runtime and the suite stays self-contained.

    python tools/gen_baseline.py

Requires: tokenizers, huggingface_hub (NOT torch, NOT transformers).
"""

import io
import json
import os
import sys

TOKENIZER_REPO = "Qwen/Qwen3-0.6B"
GGUF_REPO = "Qwen/Qwen3-0.6B-GGUF"
GGUF_FILE = "Qwen3-0.6B-Q8_0.gguf"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tests", "data", "baseline_tokenizer.json")

# Each case targets a class of pretokenizer behaviour. The multi-space and
# indentation cases are the ones that caught the GPT-2 `\s+(?!\S)` bug, where
# runs of 2+ spaces were emitted whole instead of leaving the last space to
# attach to the following word.
CASES = [
    "hello world",
    "The capital of France is Paris.",
    "  hello",
    "   spaced   out   ",
    "\ttabbed",
    "trailing   ",
    "a\n\nb",
    "don't can't won't",
    "Hello, World! 123 456",
    "3.14159 and 1e-9",
    "cafe naive jalapeno",
    "\u00e9\u00e8\u00ea \u65e5\u672c\u8a9e \u0440\u0443\u0441\u0441\u043a\u0438\u0439",
    "\U0001f600 emoji \U0001f680",
    "def f(x):\n    if x > 0:\n        return x\n    return -x",
    "<|im_start|>user\nhi<|im_end|>",
    "MixedCASE_snake_case-kebab.dot",
]


def main():
    try:
        from tokenizers import Tokenizer
        from huggingface_hub import hf_hub_download
    except ImportError as e:
        raise SystemExit("missing fixture tooling (%s). pip install tokenizers huggingface_hub" % e)

    path = hf_hub_download(TOKENIZER_REPO, "tokenizer.json")
    tok = Tokenizer.from_file(path)

    cases = []
    for text in CASES:
        ids = tok.encode(text, add_special_tokens=False).ids
        cases.append({"text": text, "ids": ids})

    doc = {
        "_comment": "Generated by tools/gen_baseline.py. Do not hand-edit.",
        "tokenizer_repo": TOKENIZER_REPO,
        "gguf_repo": GGUF_REPO,
        "gguf_file": GGUF_FILE,
        "cases": cases,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print("wrote %s (%d cases)" % (os.path.relpath(OUT, ROOT), len(cases)))


if __name__ == "__main__":
    sys.exit(main())
