"""The layered HF reference: HF's own Qwen3-MoE, Qwen3.5 and Qwen3.5-MoE modules, one decoder layer's weights in memory at a time.

    python tools/gen_layered_reference.py goldens --repo Qwen/Qwen3.5-9B --revision SHA --gguf FILE.gguf --output-dir DIR [--gguf-repo REPO --gguf-revision SHA] [--file-exact]
    python tools/gen_layered_reference.py equality --output FILE [--repo REPO --revision SHA --layers N]

From the 9B up, a qwen35 model's float32 forward does not fit host memory whole.
This runs the calls of transformers' Qwen3_5TextModel.forward in its order: the embedding, the model's own rotary embedding and masks, each decoder layer, the final norm and the head.
Each module's weights are read from the checkpoint's safetensors just before it runs, widened from bf16 to float32 as from_pretrained does, and released once it has run every input, so a run holds one layer, the embedding or the head at a time.
Every input runs alone, a batch of one, as the full forward runs it, so every logit is the full forward's bit for bit.
The checkpoint's config.json chooses the model: Qwen3_5ForCausalLM, or Qwen3_5MoeForCausalLM, whose decoder layers run HF's routed experts and shared expert as HF's own default experts implementation does.

goldens writes baseline_tokenizer.json, baseline_logits.json and baseline_perplexity.json into --output-dir with the writers of tools/gen_baseline.py, from the checkpoint's own weights, as the Qwen3-8B goldens are made.
The GGUF labels them: they record its SHA-256, and its F32 tensors are compared with the checkpoint's under the converter's conventions (docs/QWEN35.md), which shows the file was converted from these weights and which V-head order it stores.
With --file-exact the modules take the GGUF's own weights instead, each layer's decoded by tests/spec_decode.py just before it runs with the converter's changes undone, and it writes the logit and perplexity goldens tools/gen_baseline.py file-exact writes, labelled with the file, for a model too large to hold whole.
equality runs a checkpoint both ways, HF's full forward and the layered one, on every input the goldens take, and records the SHA-256 of each one's logits: by default Qwen/Qwen3.5-0.8B at the qwen35 tokenizer golden's commit, whole.
--layers N cuts both to the checkpoint's first N decoder layers, so a model whose full float32 forward does not fit memory is compared on the layers it has.
It exits nonzero unless every pair and every parameter is equal, and tests/reference_generator.py holds the committed records to that.

Both run offline from the HF cache, which must already hold the checkpoint at the commit given.
They need the qwen35 reference venv that docs/ASSETS.md lists, and tools/gen_baseline.py's check of it refuses other versions and an installed kernels, fla or causal_conv1d package, which HF would run in place of its torch code for the linear-attention layers.

Qwen3-MoE file-exact generation uses the existing tiny-MoE environment instead: torch 2.5.1+cpu, transformers 4.55.2 and numpy 2.2.6.
Temporary hooks load and release HF's modules during its own full forward, retaining its masks and RoPE.
Each distinct token sequence rereads the layers; it does not hold the whole model or create a widened model file.
Only config/tokenizer files are needed from the pinned checkpoint for --file-exact.
It does not define a new acceptance bound.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import time
from types import SimpleNamespace

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_baseline as generator
from qwen35 import tiled_order

# The equality check's default model is the one whose tokenizer the qwen35 tokenizer golden pins.
EQUALITY_REPO = generator.QWEN35_REPO
EQUALITY_REVISION = generator.QWEN35_REVISION
# The text model type of a checkpoint's config.json, and the transformers config and model classes that run it.
MODELS = {"qwen3_5_text": ("Qwen3_5TextConfig", "Qwen3_5ForCausalLM"),
          "qwen3_5_moe_text": ("Qwen3_5MoeTextConfig", "Qwen3_5MoeForCausalLM"),
          "qwen3_moe": ("Qwen3MoeConfig", "Qwen3MoeForCausalLM")}
# A decoder layer's key, as a checkpoint stores it or as the model names it, with the layer's index.
LAYER_KEY = re.compile(r"model\.(?:language_model\.)?layers\.(\d+)\.")
COMMENT = ("Generated by tools/gen_layered_reference.py goldens from the full-precision reference: HF's own decoder layers run one at a time, "
           "on the checkpoint's weights widened to float32, equal to its full forward. Do not hand-edit.")
FILE_EXACT_COMMENT = ("Generated by tools/gen_layered_reference.py goldens --file-exact: HF's own decoder layers run one at a time, "
                      "on the GGUF file's own weights as tests/spec_decode.py decodes them. Do not hand-edit.")


def reference_rows(tok):
    """Every token row the golden writers of tools/gen_baseline.py run, labelled, as [1, N] tensors: each logit prompt, the perplexity text whole, then each window of its cases."""
    rows = [("logits %d" % i, tok(text, add_special_tokens=False, return_tensors="pt").input_ids)
            for i, text in enumerate(generator.LOGIT_PROMPTS)]
    ids = tok(generator.ppl_text(), add_special_tokens=False, return_tensors="pt").input_ids
    rows.append(("perplexity", ids))
    for context, limit in generator.PPL_WINDOWS:
        rows += [("perplexity %d/%d [%d, %d)" % (context, limit, start, end), ids[:, start:end])
                 for start, end in generator.ppl_window_bounds(ids.shape[1], context, limit)]
    return rows


def row_labels(prompts, text_tokens):
    """The labels reference_rows gives for `prompts` logit prompts and a perplexity text of `text_tokens` tokens."""
    labels = ["logits %d" % i for i in range(prompts)] + ["perplexity"]
    for context, limit in generator.PPL_WINDOWS:
        labels += ["perplexity %d/%d [%d, %d)" % (context, limit, start, end)
                   for start, end in generator.ppl_window_bounds(text_tokens, context, limit)]
    return labels


def runtime(threads, directory=None):
    """The model family's pinned HF environment, offline, on `threads` CPU threads."""
    kind = None
    if directory is not None:
        with open(os.path.join(directory, "config.json"), encoding="utf-8") as f:
            raw = json.load(f)
        kind = raw.get("text_config", raw).get("model_type")
    if kind == "qwen3_moe":
        torch, transformers = generator.qwen3moe_environment()
    else:
        torch, transformers, _ = generator.qwen35_environment()
    torch.set_num_threads(threads)
    return torch, transformers


def snapshot(repo, revision):
    """The HF cache's directory for the checkpoint at `revision`, which holds the files the cache has of it."""
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    from huggingface_hub import hf_hub_download
    return os.path.dirname(hf_hub_download(repo, "config.json", revision=revision, local_files_only=True))


def past_cut(key, cut):
    """Whether `key` belongs to a decoder layer at or past `cut`, the layer count a model was cut to; None cuts nothing."""
    match = LAYER_KEY.match(key)
    return cut is not None and match is not None and int(match[1]) >= cut


def checkpoint_plan(directory, model, cut=None):
    """Where each parameter of `model` is stored in the checkpoint in `directory`, {name: (file, key)}, with the checkpoint keys the model does not take.
    Keys are renamed by transformers' own loading rules for the model, and a rule that would reshape a tensor, a key the model does not take other than the ones a qwen35 load may leave unused (tools/gen_baseline.py, QWEN35_UNUSED) or the layers past `cut` of a model cut to its first layers, and a parameter no key gives other than a tied head are refused."""
    from safetensors import safe_open
    moe = getattr(model.config, "model_type", None) == "qwen3_moe"
    if not moe:
        from transformers.conversion_mapping import get_model_conversion_mapping
        from transformers.core_model_loading import WeightConverter, WeightRenaming, rename_source_key

    index = os.path.join(directory, "model.safetensors.index.json")
    if os.path.exists(index):
        with open(index, encoding="utf-8") as f:
            stored = json.load(f)["weight_map"]
    else:
        with safe_open(os.path.join(directory, "model.safetensors"), framework="pt") as f:
            stored = {key: "model.safetensors" for key in f.keys()}
    if not moe:
        mapping = get_model_conversion_mapping(model)
        renamings = [t for t in mapping if isinstance(t, WeightRenaming)]
        converters = [t for t in mapping if isinstance(t, WeightConverter)]
    meta = model.state_dict()
    prefix = model.base_model_prefix
    plan, unexpected = {}, []
    # As transformers' loader renames them: every renaming, then at most one converter, then the base model's prefix.
    for key in sorted(stored):
        name, converter = (key, None) if moe else rename_source_key(key, renamings, converters, prefix, meta)
        if not moe and name not in meta and key in meta:
            name, converter = rename_source_key(key, [], [], prefix, meta)
        if name not in meta:
            unexpected.append(key)
            continue
        if converter is not None:
            raise SystemExit("%s: transformers converts %s on load, and the layered reference reads tensors as stored" % (directory, key))
        if name in plan:
            raise SystemExit("%s: %s and %s both give %s" % (directory, plan[name][1], key, name))
        plan[name] = (stored[key], key)
    stray = [key for key in unexpected if not (not moe and generator.QWEN35_UNUSED.match(key)) and not past_cut(key, cut)]
    if stray:
        raise SystemExit("%s: %d checkpoint keys the model neither takes nor ignores, such as %s" % (directory, len(stray), stray[0]))
    tied = {"lm_head.weight"} if model.config.tie_word_embeddings else set()
    missing = set(meta) - set(plan) - tied
    if missing:
        raise SystemExit("%s: no checkpoint key gives %s" % (directory, ", ".join(sorted(missing))))
    return plan, unexpected


def text_model(transformers, directory, layers=None):
    """The causal model class and text config of the checkpoint in `directory`, with eager attention, cut to its first `layers` decoder layers when given."""
    with open(os.path.join(directory, "config.json"), encoding="utf-8") as f:
        raw = json.load(f)
    kind = raw.get("text_config", raw).get("model_type")
    if kind not in MODELS:
        raise SystemExit("%s holds a %s model, and the layered reference runs %s" % (directory, kind, " and ".join(sorted(MODELS))))
    config_class, causal = (getattr(transformers, name) for name in MODELS[kind])
    config = config_class.from_pretrained(directory, local_files_only=True)
    config._attn_implementation = "eager"
    if layers is not None:
        if not 0 < layers <= config.num_hidden_layers:
            raise SystemExit("%s has %d decoder layers, not %d" % (directory, config.num_hidden_layers, layers))
        config.num_hidden_layers = layers
        if hasattr(config, "layer_types"):
            config.layer_types = config.layer_types[:layers]
    return causal, config


class FileWeights:
    """The GGUF's own HF parameters, one module at a time, through gen_baseline's architecture mapping and spec_decode's exact widening."""

    def __init__(self, path):
        import spec_decode
        self.gguf = spec_decode.GGUF(path)
        self.moe = self.gguf.value("general.architecture") == "qwen3moe"
        if self.moe:
            from f32 import hf_name
            self.outside = {hf_name(t.name): t.name for t in self.gguf.tensors if not t.name.startswith("blk.")}
        else:
            outside = generator.qwen35_names()[0]
            self.outside = {hf: gguf for gguf, (hf, _) in outside.items()}
        self.types = {}
        self.seen = set()

    def read(self, torch, names):
        """The parameters `names`, all of one decoder layer or all outside the layers, decoded from the file; a parameter the file lacks or a tensor of that layer the names lack is refused."""
        import numpy
        layer = {match[1] for match in map(LAYER_KEY.match, names) if match}
        if layer:
            prefix = "blk.%s." % layer.pop()
            tensors = [t for t in self.gguf.tensors if t.name.startswith(prefix)]
        else:
            wanted = {self.outside.get(name) for name in names}
            tensors = [t for t in self.gguf.tensors if t.name in wanted]
        got = {}
        decode = generator.qwen3moe_tensors if self.moe else generator.qwen35_tensors
        for name, shape, values, type_name in decode(self.gguf, True, tensors):
            if name in got:
                raise SystemExit("the GGUF gives parameter %s more than once" % name)
            got[name] = torch.from_numpy(numpy.ascontiguousarray(values, dtype=numpy.float32)).reshape(shape)
            if not self.moe or name not in self.seen:
                self.types[type_name] = self.types.get(type_name, 0) + 1
                self.seen.add(name)
        if set(got) != set(names):
            raise SystemExit("the GGUF gives %s where the model takes %s" % (sorted(set(got) - set(names))[:3], sorted(set(names) - set(got))[:3]))
        return got


class Layered:
    """The checkpoint's HF causal model, cut to its first `layers` decoder layers when given, built on the meta device, whose modules hold weights only while they run.
    With `gguf`, the weights are that file's own (FileWeights) and the checkpoint gives the model's config and parameter names.
    run() computes the logits of a list of token rows; calling it as a model, model(ids, use_cache=False), returns the logits run() computed for those ids."""

    def __init__(self, torch, directory, layers=None, gguf=None):
        import transformers
        self.torch = torch
        self.directory = directory
        self.file = FileWeights(gguf) if gguf else None
        causal, config = text_model(transformers, directory, layers)
        with torch.device("meta"):
            self.model = causal(config)
        self.model.eval().requires_grad_(False)
        if self.model.config._attn_implementation != "eager":
            raise SystemExit("the model runs %s attention, not eager" % self.model.config._attn_implementation)
        # The inverse frequencies are a buffer computed at construction, which the meta device leaves without values.
        self.rotary = type(self.model.model.rotary_emb)(config=self.model.model.config)
        self.moe = config.model_type == "qwen3_moe"
        if self.moe and self.file:
            if not self.file.moe:
                raise SystemExit("qwen3_moe reference needs a qwen3moe GGUF")
            for t in self.file.gguf.tensors:
                match = re.match(r"blk\.(\d+)\.", t.name)
                if match and int(match[1]) >= config.num_hidden_layers:
                    raise SystemExit("GGUF layer %s is past the reference model" % match[1])
            self.plan, self.unexpected = {}, []
        else:
            self.plan, self.unexpected = checkpoint_plan(directory, self.model, layers)
        self.logits = {}

    def experts(self):
        """The experts implementation HF's default gives a routed model, which from_pretrained's model runs too, or None for a dense one."""
        return getattr(self.model.config, "_experts_implementation", None)

    def source(self, name):
        """The checkpoint parameter that gives the model's parameter `name`: a tied head reads the embedding."""
        return "model.embed_tokens.weight" if name == "lm_head.weight" and self.model.config.tie_word_embeddings else name

    def read(self, names):
        """The model's parameters `names` as the checkpoint stores them, widened to float32 as from_pretrained does, or as the GGUF file of a file-exact run holds them.
        Each file is mapped only while its tensors are copied out, so no page of it stays resident after."""
        if self.file is not None:
            tensors = self.file.read(self.torch, sorted({self.source(name) for name in names}))
            return {name: tensors[self.source(name)] for name in names}
        from safetensors import safe_open
        where = {name: self.plan[self.source(name)] for name in names}
        tensors = {}
        for file in sorted({file for file, _ in where.values()}):
            with safe_open(os.path.join(self.directory, file), framework="pt", device="cpu") as reader:
                for name, (source, key) in where.items():
                    if source == file:
                        tensors[name] = reader.get_tensor(key).to(dtype=self.torch.float32, copy=True)
        return tensors

    def load(self, module, prefix):
        """Give `module`, named `prefix` in the model, its parameters from the checkpoint."""
        state = self.read([prefix + name for name, _ in module.named_parameters()])
        module.load_state_dict({name[len(prefix):]: value for name, value in state.items()}, strict=True, assign=True)
        if any(t.is_meta for t in list(module.parameters()) + list(module.buffers())):
            raise SystemExit("%s holds a tensor the checkpoint does not give" % prefix)

    def release(self, module):
        module.to("meta")

    def run(self, rows, on_layer=None):
        """The logits at every position of each [1, N] row in `rows` that has none yet, computed layer by layer; `on_layer(name, module)` sees each decoder layer and the final norm while their weights are loaded."""
        if self.moe:
            # HF owns its complete attention/mask/rotary and MoE forward.
            # Load and release its modules around those calls, without recreating that math.
            text = self.model.model
            text.rotary_emb = self.rotary
            modules = [("model.embed_tokens", text.embed_tokens)]
            modules += [("model.layers.%d" % i, layer) for i, layer in enumerate(text.layers)]
            modules += [("model.norm", text.norm), ("lm_head", self.model.lm_head)]
            hooks = []
            try:
                for name, module in modules:
                    def before(module, args, name=name):
                        self.load(module, name + ".")
                        if on_layer and (name.startswith("model.layers.") or name == "model.norm"):
                            on_layer(name, module)
                    hooks.append(module.register_forward_pre_hook(before))
                    hooks.append(module.register_forward_hook(lambda module, args, output: self.release(module)))
                with self.torch.inference_mode():
                    for ids in rows:
                        key = tuple(ids[0].tolist())
                        if key not in self.logits:
                            self.logits[key] = self.model(ids, use_cache=False).logits
            finally:
                for hook in hooks:
                    hook.remove()
                for _, module in modules:
                    self.release(module)
            return
        from transformers.masking_utils import create_causal_mask, create_recurrent_attention_mask
        torch = self.torch
        text, config = self.model.model, self.model.model.config
        todo = {}
        for ids in rows:
            todo.setdefault(tuple(ids[0].tolist()), ids)
        todo = [(key, ids) for key, ids in todo.items() if key not in self.logits]
        states = []
        with torch.inference_mode():
            # Qwen3_5TextModel.forward with no cache and no attention mask, from its embedding to its first layer; with no cache, no token has been seen before the row.
            self.load(text.embed_tokens, "model.embed_tokens.")
            for _, ids in todo:
                embeds = text.embed_tokens(ids)
                position_ids = torch.arange(embeds.shape[1], device=embeds.device) + 0
                position_ids = position_ids.view(1, 1, -1).expand(4, embeds.shape[0], -1)
                text_position_ids, position_ids = position_ids[0], position_ids[1:]
                mask_kwargs = {"config": config, "inputs_embeds": embeds, "attention_mask": None,
                               "past_key_values": None, "position_ids": text_position_ids}
                masks = {"full_attention": create_causal_mask(**mask_kwargs),
                         "linear_attention": create_recurrent_attention_mask(**mask_kwargs)}
                states.append({"hidden": embeds, "rope": self.rotary(embeds, position_ids),
                               "masks": masks, "positions": text_position_ids})
            self.release(text.embed_tokens)
            for index, layer in enumerate(text.layers[: config.num_hidden_layers]):
                self.load(layer, "model.layers.%d." % index)
                if on_layer:
                    on_layer("model.layers.%d" % index, layer)
                for state in states:
                    state["hidden"] = layer(state["hidden"], position_embeddings=state["rope"],
                                            attention_mask=state["masks"][config.layer_types[index]],
                                            position_ids=state["positions"], past_key_values=None, use_cache=False)
                self.release(layer)
            # The final norm, then Qwen3_5ForCausalLM's head over every position.
            self.load(text.norm, "model.norm.")
            self.load(self.model.lm_head, "lm_head.")
            if on_layer:
                on_layer("model.norm", text.norm)
            for (key, _), state in zip(todo, states):
                hidden = text.norm(state["hidden"])
                self.logits[key] = self.model.lm_head(hidden[:, slice(0, None), :])
            self.release(text.norm)
            self.release(self.model.lm_head)

    def __call__(self, ids, use_cache=False):
        key = tuple(ids[0].tolist())
        if key not in self.logits:
            raise KeyError("the layered reference did not run this row of %d tokens" % len(key))
        return SimpleNamespace(logits=self.logits[key])


def float32_steps(a, b):
    """How many float32 steps separate each pair of `a` and `b`, counted across zero, with -0 and +0 the same value."""
    import numpy

    def ordered(x):
        bits = numpy.ascontiguousarray(x, dtype=numpy.float32).view(numpy.int32).astype(numpy.int64)
        return numpy.where(bits < 0, -(bits & 0x7FFFFFFF), bits)
    return numpy.abs(ordered(a) - ordered(b))


class Provenance:
    """A GGUF file's F32 tensors against the checkpoint's parameters under the converter's conventions (docs/QWEN35.md, What the converter folds).
    Every norm but ssm_norm is stored as 1 + w summed in float32, ssm_a as -exp(A_log), ssm_conv1d without its middle axis, and the V side in tiled order; a routed layer's router and shared-expert gate are stored as they are.
    ssm_a is computed as torch computes exp in float32 here, and another machine's exp can round a value to the next float32, so a differing tensor records how many values differ and by how many float32 steps at most.
    ssm_dt.bias is also compared in HF's grouped order, which a file converted in tiled order with Hv above Hk must not match.
    The record names any F32 tensor of the file that the decoder layers give nothing to compare with, such as an MTP block's norms."""

    def __init__(self, path, config):
        import numpy
        import spec_decode
        self.np, self.spec = numpy, spec_decode
        self.gguf = spec_decode.GGUF(path)
        self.by_name = {t.name: t for t in self.gguf.tensors}
        self.k_heads, self.v_heads = config.linear_num_key_heads, config.linear_num_value_heads
        self.key_width = config.linear_num_key_heads * config.linear_key_head_dim
        self.tiled = numpy.array(tiled_order(self.k_heads, self.v_heads))
        self.equal, self.differ, self.linear_layers, self.grouped = 0, [], 0, 0
        self.compared = set()

    def values(self, name):
        tensor = self.by_name[name]
        if tensor.type != self.spec.F32:
            raise SystemExit("%s is %s, not F32" % (name, self.spec.type_name(tensor.type)))
        return self.gguf.decode(tensor).reshape(list(reversed(tensor.shape)))

    def compare(self, name, expected):
        self.compared.add(name)
        got = self.values(name)
        if got.shape != expected.shape:
            self.differ.append({"tensor": name, "shape": list(got.shape), "expected_shape": list(expected.shape)})
        elif self.np.array_equal(got, expected):
            self.equal += 1
        else:
            steps = float32_steps(got, expected)
            self.differ.append({"tensor": name, "values": int((steps != 0).sum()), "of": int(steps.size), "max_float32_steps": int(steps.max())})

    def __call__(self, name, module):
        np = self.np
        one = np.float32(1)

        def value(parameter):
            return parameter.detach().numpy()

        if name == "model.norm":
            self.compare("output_norm.weight", one + value(module.weight))
            return
        blk = "blk.%d." % int(name.rsplit(".", 1)[1])
        self.compare(blk + "attn_norm.weight", one + value(module.input_layernorm.weight))
        self.compare(blk + "post_attention_norm.weight", one + value(module.post_attention_layernorm.weight))
        if module.block_type == "linear_attention":
            mixer = module.linear_attn
            self.compare(blk + "ssm_dt.bias", value(mixer.dt_bias)[self.tiled])
            self.compare(blk + "ssm_a", (-mixer.A_log.exp()).numpy()[self.tiled])
            self.compare(blk + "ssm_norm.weight", value(mixer.norm.weight))
            conv = value(mixer.conv1d.weight)[:, 0, :]
            v = conv[2 * self.key_width:].reshape(self.v_heads, -1, conv.shape[1])[self.tiled].reshape(-1, conv.shape[1])
            self.compare(blk + "ssm_conv1d.weight", np.concatenate([conv[:2 * self.key_width], v]))
            self.grouped += int(np.array_equal(self.values(blk + "ssm_dt.bias"), value(mixer.dt_bias)))
            self.linear_layers += 1
        else:
            self.compare(blk + "attn_q_norm.weight", one + value(module.self_attn.q_norm.weight))
            self.compare(blk + "attn_k_norm.weight", one + value(module.self_attn.k_norm.weight))
        # A routed layer's router and shared-expert gate, the gate's [1, E] written as a vector, where the file keeps them in F32.
        if hasattr(module.mlp, "shared_expert_gate"):
            for name, parameter in ((blk + "ffn_gate_inp.weight", module.mlp.gate.weight),
                                    (blk + "ffn_gate_inp_shexp.weight", module.mlp.shared_expert_gate.weight[0])):
                if self.by_name[name].type == self.spec.F32:
                    self.compare(name, value(parameter))

    def record(self):
        record = {"f32_tensors_compared": self.equal + len(self.differ), "equal": self.equal, "differ": self.differ,
                  "v_heads": "%d V heads over %d K heads, compared in tiled order" % (self.v_heads, self.k_heads),
                  "dt_bias_equal_in_grouped_order": "%d of %d linear-attention layers" % (self.grouped, self.linear_layers)}
        uncompared = [t.name for t in self.gguf.tensors if t.type == self.spec.F32 and t.name not in self.compared]
        if uncompared:
            record["f32_not_compared"] = uncompared
        return record


def file_sha256(path):
    from baseline_8b import file_sha256 as digest
    return digest(Path(path))


def safetensors_sha256(directory):
    names = sorted(name for name in os.listdir(directory) if name.endswith(".safetensors"))
    with ThreadPoolExecutor(max_workers=4) as pool:
        return dict(zip(names, pool.map(lambda name: file_sha256(os.path.join(directory, name)), names)))


def check_tokenizer(tok, directory):
    """The ids the golden writers take from transformers' tokenizer must be those of the checkpoint's tokenizer.json, whose pretokenizer llmx follows."""
    from tokenizers import Tokenizer
    raw = Tokenizer.from_file(os.path.join(directory, "tokenizer.json"))
    for text in list(generator.LOGIT_PROMPTS) + [generator.ppl_text()]:
        ids = tok(text, add_special_tokens=False).input_ids
        if ids != raw.encode(text, add_special_tokens=False).ids:
            raise SystemExit("transformers' tokenizer and tokenizer.json give different ids for %r" % text[:40])


def peak_gib():
    if sys.platform == "win32":
        import ctypes
        from ctypes import wintypes

        class Counters(ctypes.Structure):
            _fields_ = [("cb", wintypes.DWORD), ("PageFaultCount", wintypes.DWORD)] + [
                (name, ctypes.c_size_t) for name in ("PeakWorkingSetSize", "WorkingSetSize", "QuotaPeakPagedPoolUsage",
                                                    "QuotaPagedPoolUsage", "QuotaPeakNonPagedPoolUsage", "QuotaNonPagedPoolUsage",
                                                    "PagefileUsage", "PeakPagefileUsage")]

        kernel = ctypes.WinDLL("kernel32", use_last_error=True)
        psapi = ctypes.WinDLL("psapi", use_last_error=True)
        kernel.GetCurrentProcess.restype = wintypes.HANDLE
        psapi.GetProcessMemoryInfo.argtypes = [wintypes.HANDLE, ctypes.POINTER(Counters), wintypes.DWORD]
        counters = Counters()
        counters.cb = ctypes.sizeof(counters)
        if not psapi.GetProcessMemoryInfo(kernel.GetCurrentProcess(), ctypes.byref(counters), counters.cb):
            raise ctypes.WinError(ctypes.get_last_error())
        return counters.PeakWorkingSetSize / 2 ** 30
    import resource
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / (2 ** 30 if sys.platform == "darwin" else 2 ** 20)


def label_golden(path, extra, comment=COMMENT):
    """Put this reference's `comment` on a golden the writers of tools/gen_baseline.py wrote, and the fields of `extra` it lacks after its GGUF's file name, or after the reference's metadata in a golden that names no GGUF."""
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    after = "gguf_file" if "gguf_file" in doc else "transformers_version"
    labelled = {}
    for key, value in doc.items():
        labelled[key] = comment if key == "_comment" else value
        if key == after:
            labelled.update((k, v) for k, v in extra.items() if k not in doc)
    if not set(extra) <= set(labelled):
        raise SystemExit("%s has neither gguf_file nor transformers_version to label after" % path)
    generator._write(path, labelled)


def writer_args(args, weights=None):
    """The arguments tools/gen_baseline.py's golden writers read, for the checkpoint and GGUF of a goldens run, with the `weights` record of a file-exact one."""
    return SimpleNamespace(repo=args.repo, revision=args.revision, threads=args.threads, output_dir=args.output_dir,
                           gguf_repo=args.gguf_repo, gguf_file=os.path.basename(args.gguf),
                           weights_gguf=args.gguf if weights else None, weights=weights)


def goldens(args):
    directory = snapshot(args.repo, args.revision)
    torch, transformers = runtime(args.threads, directory)
    from transformers import AutoTokenizer
    with open(os.path.join(directory, "config.json"), encoding="utf-8") as f:
        moe = json.load(f).get("model_type") == "qwen3_moe"
    if moe and not args.file_exact:
        raise SystemExit("qwen3_moe goldens require --file-exact")
    start = time.time()
    checkpoint = None if moe and args.file_exact else safetensors_sha256(directory)
    gguf = {"gguf_repo": args.gguf_repo, "gguf_file": os.path.basename(args.gguf), "gguf_revision": args.gguf_revision,
            "gguf_sha256": file_sha256(args.gguf), "gguf_bytes": os.path.getsize(args.gguf)}
    print("hashed the checkpoint and the GGUF in %.1f s" % (time.time() - start), flush=True)
    tok = AutoTokenizer.from_pretrained(args.repo, revision=args.revision, local_files_only=True)
    rows = reference_rows(tok)
    check_tokenizer(tok, directory)
    layered = Layered(torch, directory, gguf=args.gguf if args.file_exact else None)
    start = time.time()
    if args.file_exact:
        return file_exact(args, torch, transformers, tok, rows, layered, gguf, start)
    provenance = Provenance(args.gguf, layered.model.config)
    layered.run([ids for _, ids in rows], on_layer=provenance)
    print("layered forward: %d rows, %d distinct, %.1f s, peak RSS %.2f GiB"
          % (len(rows), len(layered.logits), time.time() - start, peak_gib()), flush=True)
    print("GGUF provenance: %s" % json.dumps(provenance.record()), flush=True)
    writer = writer_args(args)
    os.makedirs(args.output_dir, exist_ok=True)
    generator.gen_tokenizer(writer, os.path.join(directory, "tokenizer.json"))
    generator.gen_logits(writer, (torch, transformers, tok, layered))
    generator.gen_perplexity(writer, (torch, transformers, tok, layered))
    reference = {"layered": {
        "weights": "the checkpoint's own bf16 safetensors widened to float32, not the GGUF's",
        "safetensors_sha256": checkpoint,
        "unexpected_keys_ignored": len(layered.unexpected),
        "gguf_provenance": provenance.record()}}
    if layered.experts():
        reference["layered"]["experts_implementation"] = layered.experts()
    label_golden(os.path.join(args.output_dir, "baseline_tokenizer.json"), gguf)
    for name in ("baseline_logits.json", "baseline_perplexity.json"):
        label_golden(os.path.join(args.output_dir, name), dict(gguf, **reference))
    print("peak RSS %.2f GiB" % peak_gib(), flush=True)


def file_exact(args, torch, transformers, tok, rows, layered, gguf, start):
    """The logit and perplexity goldens of HF on the GGUF's own weights, labelled with the file and the types it decoded; no tokenizer golden and no provenance, since the weights are the file's."""
    layered.run([ids for _, ids in rows])
    weights = {"file": gguf["gguf_file"], "sha256": gguf["gguf_sha256"], "bytes": gguf["gguf_bytes"],
               "repo": args.gguf_repo, "revision": args.gguf_revision, "types": dict(sorted(layered.file.types.items())),
               "decoder": "tests/spec_decode.py, numpy form", "tensors": sum(layered.file.types.values())}
    if layered.moe:
        import spec_decode
        source_types = {}
        for tensor in layered.file.gguf.tensors:
            kind = spec_decode.type_name(tensor.type)
            source_types[kind] = source_types.get(kind, 0) + 1
        weights["source_tensor_types"] = source_types
        weights["source_tensors"] = len(layered.file.gguf.tensors)
    print("layered forward on the file's weights: %d rows, %d distinct, %.1f s, peak RSS %.2f GiB, %s"
          % (len(rows), len(layered.logits), time.time() - start, peak_gib(), json.dumps(weights["types"])), flush=True)
    writer = writer_args(args, weights)
    os.makedirs(args.output_dir, exist_ok=True)
    generator.gen_logits(writer, (torch, transformers, tok, layered))
    generator.gen_perplexity(writer, (torch, transformers, tok, layered))
    reference = {"layered": {"weights": "the GGUF's own tensors as tests/spec_decode.py decodes them, the converter's changes undone"}}
    if layered.experts():
        reference["layered"]["experts_implementation"] = layered.experts()
    for name in ("baseline_logits.json", "baseline_perplexity.json"):
        label_golden(os.path.join(args.output_dir, name), dict(gguf, **reference), FILE_EXACT_COMMENT)
    print("peak RSS %.2f GiB" % peak_gib(), flush=True)


def equality(args):
    directory = snapshot(args.repo, args.revision)
    torch, transformers = runtime(args.threads, directory)
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.repo, revision=args.revision, local_files_only=True)
    rows = reference_rows(tok)
    check_tokenizer(tok, directory)
    layered = Layered(torch, directory, args.layers)
    start = time.time()
    layered.run([ids for _, ids in rows])
    layered_seconds = time.time() - start
    causal, config = text_model(transformers, directory, args.layers)
    precision = {"torch_dtype" if layered.moe else "dtype": torch.float32}
    full, info = causal.from_pretrained(args.repo, revision=args.revision, config=config, **precision,
                                        attn_implementation="eager", output_loading_info=True, local_files_only=True)
    full.eval()
    if info["missing_keys"] or any(not (not layered.moe and generator.QWEN35_UNUSED.match(k)) and not past_cut(k, args.layers) for k in info["unexpected_keys"]):
        raise SystemExit("from_pretrained misses %s or takes unexpected %s" % (sorted(info["missing_keys"]), sorted(info["unexpected_keys"])[:4]))
    if getattr(full.config, "_experts_implementation", None) != layered.experts():
        raise SystemExit("from_pretrained's model runs the %s experts implementation, and the layered one %s"
                         % (getattr(full.config, "_experts_implementation", None), layered.experts()))
    state = full.state_dict()
    equal = 0
    for names in (list(state)[i:i + 64] for i in range(0, len(state), 64)):
        equal += sum(1 for name, value in layered.read(names).items() if torch.equal(state[name], value))
    cases, start = [], time.time()
    with torch.inference_mode():
        for label, ids in rows:
            logits = full(ids, use_cache=False).logits
            mine = layered(ids).logits
            same = logits.dtype == mine.dtype and logits.shape == mine.shape and torch.equal(logits, mine)
            cases.append({"label": label, "tokens": int(ids.shape[1]),
                          "full_sha256": hashlib.sha256(logits.contiguous().numpy().tobytes()).hexdigest(),
                          "layered_sha256": hashlib.sha256(mine.contiguous().numpy().tobytes()).hexdigest(),
                          "max_abs_difference": 0.0 if same else float((logits - mine).abs().max())})
            print("  %-34s %s" % (label, "equal" if same else "differs by %g" % cases[-1]["max_abs_difference"]), flush=True)
    full_seconds = time.time() - start
    record = {
        "_comment": "Written by tools/gen_layered_reference.py equality. Do not hand-edit.",
        "reference_repo": args.repo, "reference_revision": args.revision,
        "reference_dtype": "float32", "attention": "eager", "device": "cpu", "threads": args.threads,
        "torch_version": torch.__version__, "transformers_version": transformers.__version__,
        "parameters": len(state), "parameters_equal": equal,
        "inv_freq_equal": bool(torch.equal(full.model.rotary_emb.inv_freq, layered.rotary.inv_freq)),
        "unexpected_keys_ignored": len(layered.unexpected),
    }
    if args.layers:
        record["decoder_layers"] = "the first %d, of which %d full attention" % (args.layers, args.layers if layered.moe else config.layer_types.count("full_attention"))
    if layered.experts():
        record["experts_implementation"] = layered.experts()
    record["cases"] = cases
    generator._write(args.output, record)
    same = all(c["full_sha256"] == c["layered_sha256"] for c in cases) and equal == len(state) and record["inv_freq_equal"]
    print("wrote %s: %d of %d rows and %d of %d parameters equal; layered %.1f s, full forward %.1f s, peak RSS %.2f GiB"
          % (args.output, sum(c["full_sha256"] == c["layered_sha256"] for c in cases), len(cases), equal, len(state),
             layered_seconds, full_seconds, peak_gib()), flush=True)
    return 0 if same else 1


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="The layered HF reference of a qwen3moe or qwen35 model, run offline on the CPU in float32.")
    kinds = parser.add_subparsers(dest="kind", required=True)
    make = kinds.add_parser("goldens", help="write the tokenizer, logit and perplexity goldens for a GGUF from its HF checkpoint")
    make.add_argument("--repo", required=True, help="HF repository of the checkpoint")
    make.add_argument("--revision", required=True, help="full 40-character commit SHA of the checkpoint")
    make.add_argument("--gguf", required=True, help="the GGUF the goldens are for, which they record and whose F32 tensors are compared with the checkpoint's")
    make.add_argument("--gguf-repo", help="the Hub repository the GGUF comes from, when it is known")
    make.add_argument("--gguf-revision", help="that repository's full commit SHA")
    make.add_argument("--output-dir", required=True, help="directory for the three goldens, or with --file-exact the logit and perplexity goldens")
    make.add_argument("--file-exact", action="store_true", help="run HF on the GGUF's own weights as tests/spec_decode.py decodes them, not the checkpoint's")
    make.add_argument("--threads", type=int, default=6, help="CPU threads (default: 6)")
    check = kinds.add_parser("equality", help="check the layered forward against HF's full forward, by default on Qwen3.5-0.8B")
    check.add_argument("--output", required=True, help="file for the equality record")
    check.add_argument("--repo", default=EQUALITY_REPO, help="HF repository of the checkpoint (default: %s)" % EQUALITY_REPO)
    check.add_argument("--revision", default=EQUALITY_REVISION, help="full 40-character commit SHA of the checkpoint (default: %s)" % EQUALITY_REVISION)
    check.add_argument("--layers", type=int, help="cut both forwards to the checkpoint's first N decoder layers (default: all)")
    check.add_argument("--threads", type=int, default=6, help="CPU threads (default: 6)")
    args = parser.parse_args(argv)
    if args.threads < 1:
        parser.error("--threads must be positive")
    if os.path.isdir(args.repo):
        parser.error("--repo must identify a Hub repository, not a local directory that bypasses revision pinning")
    for flag, value in (("--revision", args.revision), ("--gguf-revision", getattr(args, "gguf_revision", None))):
        if value is not None and not re.fullmatch(r"[0-9a-f]{40}", value):
            parser.error("%s must be a full 40-character lowercase commit SHA" % flag)
    if args.kind == "equality" and args.layers is not None and args.layers < 1:
        parser.error("--layers must be positive")
    if args.kind == "goldens":
        if args.gguf_revision and not args.gguf_repo:
            parser.error("--gguf-revision needs --gguf-repo")
        if not os.path.isfile(args.gguf):
            parser.error("--gguf %s is not a file" % args.gguf)
        args.output_dir = os.path.abspath(args.output_dir)
        if os.path.normcase(os.path.realpath(args.output_dir)) == os.path.normcase(os.path.realpath(generator.OUT_DIR)):
            parser.error("--output-dir cannot be the directory of the default fixtures")
    return args


def main(argv=None):
    args = parse_args(argv)
    if args.kind == "goldens":
        goldens(args)
        return 0
    return equality(args)


if __name__ == "__main__":
    sys.exit(main())
