"""Generate the chat fixtures from transformers' own chat template renderer.

tests/data/baseline_chat.json holds greedy follow-up replies of the tiny F32 model of tests/f32.py from HF Qwen3ForCausalLM, each turn's transcript rendered by transformers.
The byte-only vocabulary maps each raw byte directly to its token ID, and Latin-1 keeps generated bytes as they are.
tests/data/baseline_chat_template.json holds the pinned real templates and small feature templates with each case as transformers renders it, the templates llmx refuses, and assistant turns split as the Qwen templates split them.
Each real template also records whether chat::ChatFormat keeps an assistant turn split under it, read from Jinja's own parse of the template, how transformers' renders say a turn should be kept where they decide it, and its renders of a two-turn conversation with the turn kept that way.
The real templates are read back from that file and checked against their SHA-256; --add puts another one in.

A scan of every template a machine holds takes two steps, and leaves the committed fixtures alone.
--extract lists each distinct template in the GGUF files under the given directories with the files that hold it, with the standard library alone, so it runs where the files are.
--scan renders the templates of one or more such lists into a file of the fixture's form, which llmx-chat-template-test then checks.

Regenerating and --scan need the reference environment, an isolated Python 3.12 venv apart from the 4.55.2 one of tools/gen_baseline.py: transformers 5.17.0, Jinja2 3.1.6 and MarkupSafe 3.0.3, and for baseline_chat.json torch 2.5.1+cpu, tokenizers 0.23.2, huggingface-hub 1.33.0, safetensors 0.8.0 and numpy 2.2.6.
The generator refuses to render with another transformers or Jinja2, since only the recorded version field would show the change; running the tests needs none of these packages.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "tests/data/baseline_chat_template.json"
CHAT = ROOT / "tests/data/baseline_chat.json"
BOS, EOS = "", "<|im_end|>"
REFERENCE = {"transformers": "5.17.0", "jinja2": "3.1.6"}


def m(role, content, reasoning=None):
    message = {"role": role, "content": content}
    if reasoning is not None:
        message["reasoning_content"] = reasoning
    return message


def split_turn(text):
    """An assistant turn split as the Qwen templates split one themselves, the rule chat::assistant_turn follows: (content, reasoning), with no reasoning when the text holds no </think>."""
    if "</think>" not in text:
        return text, None
    reasoning = text.split("</think>")[0].rstrip("\n").split("<think>")[-1].lstrip("\n")
    return text.split("</think>")[-1].lstrip("\n"), reasoning


def legacy_cases():
    """The twelve conversations the Qwen3 fixture held before transformers' renderer, so the regenerated goldens compare with the old ones case for case."""
    cases, messages = [], [m("system", "You are helpful."), m("user", "Remember violet.")]
    for turn in range(3):
        if turn:
            messages += [m("assistant", "<think>Private reasoning.</think>\n\nViolet." if turn == 1 else "Violet again."),
                         m("user", "What color?" if turn == 1 else "Say it again.")]
        for complete in (False, True):
            history = messages + ([m("assistant", "<think>Reason.</think>\n\nAnswer.")] if complete else [])
            for generate in (False, True):
                cases.append(("legacy-%d-%s-%s" % (turn, "complete" if complete else "open", "gen" if generate else "nogen"),
                              [dict(x) for x in history], generate))
    return cases


SYSTEM = "You are a helpful assistant."
REPLY = "<think>\nThe user wants a color kept.\n</think>\n\nViolet it is."
# Tools as a client passes them, with text beyond ASCII and nested objects whose keys are not in sorted order, so tojson's escapes and key order both show.
TOOLS = [
    {"type": "function", "function": {
        "name": "get_weather",
        "description": "Temperature in \u00b0C for a city, such as Z\u00fcrich or \u6771\u4eac.",
        "parameters": {"type": "object",
                       "properties": {"city": {"type": "string", "description": "The city's name \u2013 in any script."},
                                      "days": {"type": "integer", "minimum": 1, "maximum": 7},
                                      "unit": {"type": "string", "enum": ["celsius", "fahrenheit"],
                                               "x-note": {"z": 1, "a": [True, None, 0.5, "\u00e9"]}}},
                       "required": ["city"]}}},
    {"type": "function", "function": {"name": "noop", "description": "  Does nothing.  ", "parameters": {"type": "object", "properties": {}}}},
]
# Tool calls with their arguments as a dict and as a JSON string, and one without the function wrapper.
CALL_DICT = {"type": "function", "function": {"name": "get_weather", "arguments": {"city": "Z\u00fcrich", "days": 3, "unit": {"b": 1, "a": ["x", None]}}}}
CALL_STRING = {"type": "function", "function": {"name": "get_weather", "arguments": "{\"city\": \"Paris\"}"}}
CALL_BARE = {"name": "noop", "arguments": {}}


def call(content, *calls):
    return {"role": "assistant", "content": content, "tool_calls": list(calls)}


def parts(*items):
    """Content as a list of parts, text given as a string."""
    return [{"type": "text", "text": x} if isinstance(x, str) else x for x in items]


# Conversations every real template renders: the legacy twelve, the same reply raw and split as a client may send it back, tool turns, tools and tool calls, content as parts, the conversations the Qwen 3.5 templates refuse, and text that JSON or whitespace handling could change.
# Each is (name, messages, add_generation_prompt), with the tools passed as a fourth item where there are any.
TEMPLATE_CASES = legacy_cases() + [
    ("user-only", [m("user", "Hello there.")], True),
    ("reply-raw", [m("system", SYSTEM), m("user", "Remember violet."), m("assistant", REPLY), m("user", "What color?")], True),
    ("reply-split", [m("system", SYSTEM), m("user", "Remember violet."), m("assistant", *split_turn(REPLY)), m("user", "What color?")], True),
    ("reply-split-last", [m("system", SYSTEM), m("user", "Remember violet."), m("assistant", *split_turn(REPLY))], False),
    ("empty-reasoning", [m("user", "Hi."), m("assistant", "Hello.", ""), m("user", "Again.")], True),
    ("tool-turns", [m("system", SYSTEM), m("user", "Weather?"), m("assistant", "Checking."), m("tool", "{\"t\": 21}"),
                    m("tool", "clear"), m("user", "Thanks.")], True),
    ("tool-last", [m("user", "Run it."), m("assistant", "Running."), m("tool", "done")], True),
    ("tool-response-user", [m("user", "Start."), m("assistant", "Started."), m("user", "<tool_response>\nok\n</tool_response>")], True),
    ("tools-system", [m("system", SYSTEM), m("user", "Weather in Z\u00fcrich?")], True, TOOLS),
    ("tools-no-system", [m("user", "Weather?")], True, TOOLS),
    ("tool-call-dict", [m("system", SYSTEM), m("user", "Weather?"), call("", CALL_DICT), m("tool", "{\"t\": 21}"), m("user", "Thanks.")], True, TOOLS),
    ("tool-call-string", [m("user", "Weather?"), call("Let me check.", CALL_STRING), m("tool", "sunny")], True, TOOLS),
    ("tool-calls-two", [m("user", "Both."), call("", CALL_BARE, CALL_DICT), m("tool", "ok"), m("tool", "done"), m("user", "Next.")], True, TOOLS),
    ("content-parts", [m("system", parts("Be brief.")), m("user", parts("Hello ", "world")), m("assistant", "Hi."),
                       m("user", parts({"type": "image"}, "What is this?"))], True),
    ("no-user", [m("system", SYSTEM)], True),
    ("empty", [], True),
    ("late-system", [m("user", "Hi."), m("system", "Late.")], True),
    ("developer", [m("developer", "Be terse."), m("user", "Hi.")], True),
    ("unknown-role", [m("narrator", "Once."), m("user", "Hi.")], True),
    ("unicode", [m("system", ""), m("user", "Gr\u00fc\u00dfe \u2013 \u4f60\u597d \U0001f642 \"q\" \\ <t> & 'a'\ttab")], True),
    ("whitespace", [m("user", "  padded  \n\n"), m("assistant", "\n\n<think>\n  spaced  \n</think>\n\n  reply  \n"), m("user", "next")], True),
    ("two-thinks", [m("user", "q"), m("assistant", "<think>a</think>b</think>c"), m("user", "r")], True),
]

# The two-turn conversation each real template renders an assistant turn in, kept as chat and the server keep it: its first turn, then the reply between it and the second.
# The replies hold no </think>, a leading <think>, only the closing tag a thinking generation prompt leaves, two closing tags, and spaces or a tab after it, and the last is the reply of the reasoning model in tests/server.py.
TURN_BEFORE = [m("system", ""), m("user", "a")]
TURN_AFTER = [m("user", "b")]
TURN_TEXTS = ["Plain reply.", "<think>\nplan\n</think>\n\nreply", "plan\n</think>\n\nreply", "<think>a</think>b</think>c",
              "<think>\nr\n</think>\n\n  reply", "<think>\nr\n</think>\n\n\treply", "qr</think>o"]

# Small templates, each over a few conversations, for the parts of the language the real templates reach only in branches their conversations do not take.
CONVERSATIONS = [
    [m("system", "S"), m("user", "U")],
    [m("system", "You are helpful."), m("user", "Hi"), m("assistant", "Hello!", "greet"), m("user", "Bye")],
    [],
]


def by_length(two, four, none):
    """A template that runs `two`, `four` or `none` as the conversation holds two messages, four or none, so one feature fails differently on each."""
    return "{%% set n = messages|length %%}{%% if n == 2 %%}%s{%% elif n == 4 %%}%s{%% else %%}%s{%% endif %%}" % (two, four, none)


FEATURES = [
    ("whitespace", "{%- for m in messages %}\n  {{ m.role }}: {{ m.content }}\n  {%+ if loop.last %}END{% endif %}\n"
                   "{# note #}\n\t{% if true -%}  x  {%- endif %}\n{%- endfor %}\n{{- ' tail ' -}}\n  after\n"),
    ("whitespace-crlf", "{% for m in messages %}\r\n  {{ m.role }}\r\n  {% if loop.first %}first{% endif +%}\r\n{% endfor %}\r\n"),
    ("macro", "{% macro wrap(x, open='[', close=']') %}{{ open ~ x ~ close }}{% endmacro %}"
              "{% set ns = namespace(n=0) %}{% macro count() %}{% set ns.n = ns.n + 1 %}{% endmacro %}"
              "{% for m in messages %}{{ wrap(m.role) }}{{ wrap(m.content, close='>') }}{{ count() }}{% endfor %}{{ ns.n }}"
              "{% macro down(n) %}{{ n }}{% if n > 0 %}{{ down(n - 1) }}{% endif %}{% endmacro %}{{ down(3) }}"),
    ("macro-scope", "{% set x = 'outer' %}{% macro show(y=x) %}{{ y }}{% set x = 'inner' %}{{ x }}{% endmacro %}"
                    "{{ show() }}{{ x }}{% set x = 'changed' %}{{ show() }}{{ show('given') }}"),
    ("slice", "{{ messages[::-1]|map(attribute='role')|join(',') }}|{{ messages[1:]|length }}|{{ 'abcdef'[1:-1:2] }}"
              "|{{ 'abcdef'[::-2] }}|{{ messages[-1:]|length }}|{{ 'abc'[5:] }}|{{ [1, 2, 3][-9:9] }}|{{ (1, 2, 3)[::2] }}"),
    ("conditional", "{{ 'yes' if messages else 'no' }}{{ ('a', 'b') }}{{ 'x' in ('x', 'y') }}{{ 'q' if false }}|"
                    "{{ (messages|length, 'n') }}{% for a, b in [(1, 2), (3, 4)] %}{{ a + b }}{% endfor %}"),
    ("tests", "{% set v = messages[0] if messages else none %}{{ v is undefined }}{{ nothing is undefined }}{{ true is true }}"
              "{{ 1 is true }}{{ false is false }}{{ 0 is false }}{{ v is mapping }}{{ 'a' is string }}{{ [] is sequence }}"
              "{{ v is iterable }}{{ 1 is number }}{{ 1 is integer }}{{ 1.5 is float }}{{ none is none }}{{ true is boolean }}"
              "{{ 9 is divisibleby 3 }}{{ 4 is even }}{{ 3 is odd }}{{ 'a' is in 'abc' }}{{ 2 is eq 2 }}{{ 'ab' is lower }}"
              "{{ v is defined }}{{ tools is none }}{{ tools is defined }}"),
    ("filters", "{% for m in messages %}{{ ('  ' ~ m.content ~ '  ')|trim }}|{{ m|string }}|{{ m.content|safe }}"
                "|{% for k, v in m|items %}{{ k }}={{ v }};{% endfor %}{% endfor %}|{{ messages|first|tojson }}"
                "|{{ messages|last|default('none') }}|{{ nothing|default('d') }}|{{ ''|default('e', true) }}"
                "|{{ 'abc'|list }}|{{ messages|map(attribute='content')|map('upper')|join('/') }}|{{ 'Mixed Case'|lower }}"
                "|{{ 'hello big-world (x)'|title }}|{{ 'aaa'|replace('a', 'b', 2) }}|{{ [3, 1, 2]|reverse|list }}|{{ 'ab'|count }}"
                "|{{ {'b': 1, 'a': 2, 'C': 3}|dictsort }}|{{ {'b': 1, 'a': 2}|dictsort(by='value', reverse=true) }}"
                "|{{ messages|map(attribute='reasoning_content', default='-')|join }}"),
    ("select", "{{ [1, 2, 3, 4]|select('odd')|list }}|{{ [1, 2, 3]|reject('odd')|list }}|{{ [0, 1, '', none, 'x']|select|list }}"
               "|{{ messages|selectattr('role', 'eq', 'user')|map(attribute='content')|list }}|{{ messages|rejectattr('reasoning_content')|list|length }}"
               "|{{ messages|selectattr('reasoning_content')|list|length }}|{{ ['a', 'b', 'c']|reject('in', ['b'])|list }}|{{ nothing|select|list }}"
               "|{{ ''|select|list }}|{{ [[1, 0], [0, 1]]|selectattr('0')|list }}|{{ {'a': 1, 'b': 2}.keys()|reject('in', ['a'])|list }}"
               "|{{ messages|selectattr('role', 'in', ['system', 'user'])|list|length }}|{{ [3, 1, 2]|select('gt', 1)|list }}"
               "|{{ messages|map('select')|map('join')|list }}"),
    ("views", "{% set d = {'a': 1, 'b': [2]} %}{{ d.keys() }}|{{ d.values() }}|{{ d.items() }}|{{ d.keys() == ['a', 'b'] }}"
              "|{{ d.keys() == d.keys() }}|{{ d.values() == d.values() }}|{% set v = d.values() %}{{ v == v }}|{{ d.items() == d.items() }}"
              "|{{ 'a' in d.keys() }}|{{ ('a', 1) in d.items() }}|{{ ['a', 1] in d.items() }}|{{ 1 in d.values() }}|{{ d.keys()|length }}"
              "|{{ d.keys()|first }}|{{ d.keys()|last }}|{{ d.keys() < d.keys() }}|{{ d.keys() <= {'a': 0, 'b': 0, 'c': 0}.keys() }}"
              "|{{ {}.keys() == {}.items() }}|{{ d.keys()[0] is defined }}|{{ [d.keys()] }}|{{ d.keys()|string }}|{{ d.keys()|join(',') }}"
              "|{{ d.keys()|reverse|list }}|{{ d.keys() is iterable }}|{{ d.keys() is sequence }}|{{ d.keys() is mapping }}"
              "|{% for k, x in d.items() %}{{ k }}{{ x }}{% endfor %}|{% for m in messages %}{{ m.keys() }}{{ m.items()|list|length }}{% endfor %}"),
    ("floats", "{{ 1 // 0.1 }} {{ -1 // 0.1 }} {{ -4.0 % 2 }} {{ 4.0 % -2 }} {{ -0.0 // 1 }} {{ 0.0 // -1 }} {{ 7.5 // -2 }}"
               " {{ 1e308 // 1e-308 }} {{ 5.5 % 2 }} {{ -5.5 % 2 }} {{ 5 % -3.0 }} {{ (0.1 + 0.2) // 0.1 }} {{ 1 / 3 }} {{ 2 ** 0.5 }}"
               " {{ 1 <= 1.0 }} {{ 'b' >= 'a' }} {{ [1, 2] <= [1, 2] }} {{ (1, 2) > (1,) }} {{ 2 is gt 1 }} {{ 2 is le 2 }}"
               " {{ 'a' is lt 'b' }} {{ 3 is ge 4 }}"),
    ("errors-concat", by_length("{{ 'a' + 1 }}", "{{ [1] + 'a' }}", "{{ (1,) + [1] }}")),
    ("errors-operands", by_length("{{ 1 + 'a' }}", "{{ 'a' * 1.5 }}", "{{ [1] * [2] }}")),
    ("errors-compare", by_length("{{ 'a' > 1 }}", "{{ 'a' <= 1 }}", "{% set d = {'a': 1} %}{{ d.values() < d.values() }}")),
    ("errors-division", by_length("{{ 1.0 // 0 }}", "{{ 1 % 0 }}", "{{ 1 / 0 }}")),
    ("errors-select", by_length("{{ [1]|select('nosuch')|list }}", "{{ 5|select|list }}", "{{ [1]|select(5)|list }}")),
    ("tojson", "{{ {'z': 1, 'a': [1, 2.5, none, true, 'x<y>&\\'\"'], 'u': '\u00e9\u4f60\U0001f642\\n\\t\x01'}|tojson }}"
               "|{{ {'z': 1, 'a': {'b': []}}|tojson(indent=2) }}|{{ {'z': 1, 'a': 2}|tojson(sort_keys=true) }}"
               "|{{ ['\u00e9']|tojson(ensure_ascii=true) }}|{{ {'a': 1}|tojson(separators=(',', ':')) }}|{{ messages|tojson }}"
               "|{{ [1e20, 1e-5, 0.1, -0.0, 100.0, 1.5e16]|tojson }}"),
    ("methods", "{% for m in messages %}{{ m.content.startswith(('H', 'U')) }}{{ m.content.endswith('!') }}"
                "{{ ('xx' ~ m.content ~ 'yy').strip('xy') }}{{ ' a '.lstrip() }}{{ ' a '.rstrip() }}"
                "{{ 'a,b,,c'.split(',') }}{{ 'a b  c'.split() }}{{ 'a,b,c'.split(',', 1) }}{{ 'aXbX'.replace('X', '-', 1) }}"
                "{{ 'hello'.find('l') }}{{ 'hello'.count('l') }}{{ m.get('role') }}{{ m.get('nope', 'dflt') }}{{ m.keys()|list }}"
                "{{ m.values()|list|length }}{{ m.items()|list|length }}{{ 'up'.upper() }}{{ 'DOWN'.lower() }}"
                "{{ \"they're here\".title() }}{{ ','.join(['a', 'b']) }}{% endfor %}"),
    ("loop", "{% for m in messages %}{{ loop.index }}{{ loop.index0 }}{{ loop.revindex }}{{ loop.revindex0 }}{{ loop.length }}"
             "{{ loop.first }}{{ loop.last }}{{ loop.previtem.role if loop.previtem else '-' }}"
             "{{ loop.nextitem.role if loop.nextitem is defined else '-' }};{% else %}empty{% endfor %}"
             "|{% for m in messages if m.role != 'system' %}{{ m.role }}{{ loop.length }}{% endfor %}"
             "|{% for i in range(10) %}{% if i == 2 %}{% continue %}{% endif %}{% if i == 5 %}{% break %}{% endif %}{{ i }}{% endfor %}"
             "|{% for i in range(5, 0, -2) %}{{ i }}{% endfor %}|{% for c in 'ab' %}{{ c }}{% endfor %}"),
    ("raise", "{% if messages|length > 2 %}{{ raise_exception('Too many messages: ' ~ messages|length) }}{% endif %}ok"),
    ("defined", "{%- if not date_string is defined %}{%- set date_string = \"26 Jul 2024\" %}{%- endif %}Today Date: {{ date_string }}"
                "|{% if tools is defined and tools is none %}T{% endif %}{% if tool_calls is not defined and system is not defined %}N{% endif %}"
                "{% if messages is defined and eos_token is defined %}M{% endif %}"
                "|{% for m in messages %}{{ m.role[0] }}{% if m.content is defined %}c{% endif %}{% if m.tool_calls is not defined %}-{% endif %}{% endfor %}"
                "|{% set x = none %}{% set ns = namespace(a=none) %}{% if x is defined and ns.a is defined and ns.b is not defined %}D{% endif %}"
                "|{% for m in messages %}{% if loop is defined %}L{% endif %}{% endfor %}{% if loop is not defined %}N{% endif %}"),
    ("soft-missing", "{% if false %}{{ x|nosuch }}{% endif %}{{ 'a'|nosuch if false else 'b' }}"
                     "{% if messages|length > 2 %}{{ 'a'|nosuch }}{% endif %}ok"),
    ("set-block", "{% set x | upper %}{% for m in messages %}{{ m.role }} {% endfor %}{% endset %}{{ x }}|{% set y %}"
                  "{% set z = 1 %}inner{% endset %}{{ y }}{{ z is defined }}"),
    ("generation", "{% for m in messages %}{% if m.role == 'assistant' %}{% generation %}{{ m.content }}{% endgeneration %}"
                   "{% else %}{{ m.content }}{% endif %}{% endfor %}"),
    ("arithmetic", "{{ 1 + 2 * 3 }} {{ 7 // 2 }} {{ -7 // 2 }} {{ 7 % -3 }} {{ -7 % 3 }} {{ 2 ** 10 }} {{ 2 ** -1 }} {{ 1 / 2 }} {{ 4 / 2 }}"
                   " {{ 0.1 + 0.2 }} {{ 7.5 // 2 }} {{ -7.5 % 2 }} {{ 'a' ~ 1 ~ none ~ true }} {{ [1] + [2] }} {{ 'ab' * 3 }} {{ 2 * (1,) }}"
                   " {{ -(messages|length) }} {{ 1 < 2 < 3 }} {{ 3 > 2 > 2 }} {{ 'b' > 'a' }} {{ [1, 2] < [1, 3] }} {{ 1 == 1.0 }} {{ true == 1 }}"
                   " {{ 1e3 }} {{ 1_000 }} {{ 12345678901234567 }} {{ 0.000001 }}"),
    ("undefined", "{{ nothing }}|{{ messages[0].nope if messages else '' }}|{{ messages[9] is defined }}"),
    ("undefined-attr", "{{ nothing.attr }}"),
    ("undefined-item", "{{ messages[5].role }}"),
    ("undefined-nested", "{{ messages[0].nope.x }}"),
    ("repr", "{{ messages[0] if messages else {} }}|{{ [1, 'a', none, true, 1.5, \"it's\"] }}|{{ (1,) }}|{{ {'a': 1} }}"
             "|{{ namespace(a=1, b='x') }}|{{ ['\\n', '\u00e9', '\\x7f'] }}"),
    ("literals", "{{ '\\x41\\u00e9\\n\\101\\q' }}|{{ \"a\" 'b' }}|{{ 'it\\'s' }}|{{ '\u00e9' }}"),
    ("scope", "{% set a = 1 %}{% for m in messages %}{% set a = a + 1 %}{{ a }}{% endfor %}{{ a }}"
              "{% if true %}{% set b = 2 %}{% endif %}{{ b }}{% set ns = namespace(c=0) %}"
              "{% for m in messages %}{% set ns.c = ns.c + loop.index %}{% endfor %}{{ ns.c }}"),
    ("dict-literal", "{% set d = {'role': 'x', 'n': 1} %}{{ d.role }}{{ d['n'] }}{{ d.items()|list }}{{ d|length }}"
                     "{{ 'role' in d }}{{ d.get('missing') }}{{ d.pop is defined }}"),
    ("loop-controls", "{% for i in range(3) %}{% for j in [] %}x{% else %}{% if i == 1 %}{% continue %}{% endif %}e{% endfor %}{{ i }}{% endfor %}"
                      "|{% for i in range(3) %}{% set s %}{{ i }}{% if i == 1 %}{% break %}{% endif %}{% endset %}{{ s }}{% endfor %}"
                      "|{{ nothing is callable }}{% for m in messages %}{{ loop is callable }}{% endfor %}{{ namespace() is callable }}"
                      "{{ raise_exception is callable }}{{ messages is callable }}|{{ {'a': [1]}|tojson(indent=70) }}{{ [1]|tojson(indent=-2) }}"),
    ("cond-undefined", "{% set a = 1 %}\n{{ a }}\n{{ (\na if false).x }}"),
    ("recursion", "{% macro down(n) %}{% if n > 0 %}{{ down(n - 1) }}{% endif %}{% endmacro %}{{ down(20) }}ok"
                  "{% if messages|length == 4 %}{{ down(100000) }}{% endif %}"),
]

# Templates llmx refuses, with why; transformers compiles some of them, and the fixture records which.
REFUSED = [
    ("include", "{% include 'other.jinja' %}", "a tag outside the supported part"),
    ("filter-block", "{% filter upper %}x{% endfilter %}", "a tag outside the supported part"),
    ("call-block", "{% macro m() %}{{ caller() }}{% endmacro %}{% call m() %}x{% endcall %}", "a tag and a macro reading caller"),
    ("raw", "{% raw %}{{ x }}{% endraw %}", "a tag outside the supported part"),
    ("recursive", "{% for m in messages recursive %}{{ m.role }}{% endfor %}", "a recursive loop"),
    ("do", "{% do messages.append(1) %}", "a tag Jinja2 has only with an extension"),
    ("groupby", "{{ messages|groupby('role') }}", "a filter outside the supported part"),
    ("escaped", "{{ messages is escaped }}", "a test outside the supported part"),
    ("select-sameas", "{{ messages|select('sameas', none)|list }}", "a test outside the supported part, named to select"),
    ("select-keyword", "{{ messages|select('eq', other=1)|list }}", "a keyword argument select does not take here"),
    ("format-method", "{{ '{}'.format(1) }}", "a method outside the supported part"),
    ("lipsum", "{{ lipsum() }}", "a global outside the supported part"),
    ("unknown-filter", "{{ messages|nosuch }}", "a filter Jinja2 does not have, outside an if"),
    ("unknown-filter-loop", "{% if true %}{% for m in messages %}{{ m|nosuch }}{% endfor %}{% endif %}", "a filter Jinja2 does not have, in a loop"),
    ("trailing", "{{ messages messages }}", "tokens after the expression"),
    ("unclosed", "{% if messages %}x", "an if without its endif"),
    ("unbalanced", "{{ (messages }}", "an unbalanced parenthesis"),
    ("unterminated", "{{ 'abc }}", "a string without its end"),
    ("multi-index", "{{ messages[0, 1] }}", "a subscript of two indexes"),
    ("star-args", "{% macro m(a) %}{% endmacro %}{{ m(*messages) }}", "unpacked call arguments"),
    ("varargs", "{% macro m() %}{{ varargs }}{% endmacro %}", "a macro reading varargs"),
    ("break-outside", "{% break %}", "a break outside a loop"),
    ("hex-literal", "{{ 0x1F }}", "a hex literal"),
    ("block", "{% block body %}x{% endblock %}", "a tag outside the supported part"),
    ("loop-target", "{% for loop in messages %}{{ loop }}{% endfor %}", "a loop whose target is named loop"),
    ("set-loop", "{% for m in messages %}{% set loop = 5 %}{{ loop }}{% endfor %}", "loop assigned inside a loop"),
    ("set-loop-macro", "{% for m in messages %}{% macro f() %}{% set loop = 1 %}{% endmacro %}{% endfor %}", "loop assigned in a macro inside a loop"),
    ("duplicate-parameter", "{% macro f(a, a) %}{{ a }}{% endmacro %}{{ f(1, 2) }}", "a macro naming a parameter twice"),
    ("repeated-keyword", "{% macro f(a) %}{{ a }}{% endmacro %}{{ f(a=1, a=2) }}", "a keyword argument given twice"),
    ("deep-sum", "{{ " + " + ".join(["1"] * 1000) + " }}", "an expression nested past the limit, a chain of 1000 sums"),
    ("deep-attributes", "{{ messages" + ".x" * 300 + " }}", "an expression nested past the limit, a chain of 300 attributes"),
    ("deep-filters", "{{ 'a'" + "|trim" * 300 + " }}", "an expression nested past the limit, a chain of 300 filters"),
    ("deep-statements", "{% if true %}" * 300 + "{% endif %}" * 300, "statements nested past the limit"),
]

SPLITS = ["no think here", "<think>\nplan\n</think>\n\nreply", "plan</think>reply", "\n\nplan\n\n</think>\n\n\nreply\n",
          "<think>a</think>b</think>c", "x<think>y<think>z</think>w", "</think>", "<think></think>",
          "  <think>\n spaced \n</think>\n  reply  ", "", "<think>\nunfinished reasoning"]


def gguf_templates(path):
    """The chat templates a GGUF file's metadata holds, by key, read without the tensor data."""
    sizes = {0: 1, 1: 1, 2: 2, 3: 2, 4: 4, 5: 4, 6: 4, 7: 1, 10: 8, 11: 8, 12: 8}
    found = {}
    with open(path, "rb") as f:
        def read(fmt):
            return struct.unpack("<" + fmt, f.read(struct.calcsize("<" + fmt)))

        def text():
            (n,) = read("Q")
            return f.read(n)

        def skip(kind):
            if kind == 8:
                text()
            elif kind == 9:
                inner, count = read("IQ")
                if inner in sizes:
                    f.seek(sizes[inner] * count, 1)
                else:
                    for _ in range(count):
                        skip(inner)
            else:
                f.seek(sizes[kind], 1)

        if f.read(4) != b"GGUF":
            return found
        _, _, count = read("IQQ")
        for _ in range(count):
            key = text().decode("utf-8", "replace")
            (kind,) = read("I")
            if key.startswith("tokenizer.chat_template") and kind == 8:
                found[key] = text().decode("utf-8", "surrogateescape")
            else:
                skip(kind)
    return found


def attempt(render, template, messages, generate, tools=None):
    """The render as a fixture records it: {"expected": text}, or the error it raises."""
    try:
        return {"expected": render(template, messages, generate, tools)}
    except Exception as e:
        return {"error_type": type(e).__name__, "error": str(e)}


def render_all(render, template, cases):
    """Each (name, messages, generate[, tools]) as transformers renders it, or the error it raises."""
    out = []
    for name, messages, generate, *tools in cases:
        case = {"name": name, "messages": messages, "generate": generate}
        if tools:
            case["tools"] = tools[0]
        case.update(attempt(render, template, messages, generate, *tools))
        out.append(case)
    return out


def splits_turns(parse, template):
    """Whether chat::ChatFormat keeps an assistant turn split under this template, its rule read from Jinja's own parse of it rather than llmx's: the template reads reasoning_content, as an attribute, a constant subscript, a get() or a filter's attribute, and does not split text at the constant '</think>'."""
    from jinja2 import nodes

    def text(node):
        return node.value if isinstance(node, nodes.Const) and isinstance(node.value, str) else None

    reads = splits = False
    for n in parse(template).find_all((nodes.Getattr, nodes.Getitem, nodes.Call, nodes.Filter)):
        names = []
        if isinstance(n, nodes.Getattr):
            names.append(n.attr)
        elif isinstance(n, nodes.Getitem):
            names.append(text(n.arg))
        elif isinstance(n, nodes.Call) and isinstance(n.node, nodes.Getattr) and n.args:
            if n.node.attr == "get":
                names.append(text(n.args[0]))
            splits |= n.node.attr == "split" and text(n.args[0]) == "</think>"
        elif isinstance(n, nodes.Filter):
            if n.name in ("selectattr", "rejectattr") and n.args:
                names += (text(n.args[0]) or "").split(".")
            if n.name == "map":
                names += [part for kw in n.kwargs if kw.key == "attribute" for part in (text(kw.value) or "").split(".")]
        reads |= "reasoning_content" in names
    return reads and not splits


def reference_keeps(render, template):
    """How transformers' renders say a conversation should keep an assistant turn, where they decide it: "whole" when the template treats a </think> in a turn itself, "split" when it shows reasoning passed apart in reasoning_content and leaves </think> alone, and None when they do not decide.
    The turn is the last message where a template shows only the latest reasoning, and before a user message where the template needs the last message to be the user's.
    A template treats </think> itself when a turn holding it renders otherwise than the same turn with the tag renamed; the turn is written with and without the newlines the Qwen templates put around a split, since a template that splits it may write it back as it was."""
    texts = ["<think>\nprobe reasoning\n</think>\n\nprobe reply", "<think>probe reasoning</think>probe reply"]
    for after, generate in (([], False), ([m("user", "b")], True)):
        try:
            def turn(message):
                return render(template, [m("user", "a"), message] + after, generate)

            apart = turn(m("assistant", "probe reply", "probe reasoning"))
            plain = turn(m("assistant", "probe reply"))
            handled = any(turn(m("assistant", t)) != turn(m("assistant", t.replace("</think>", "</thonk>"))).replace("</thonk>", "</think>")
                          for t in texts)
        except Exception:
            continue
        if handled:
            return "whole"
        return "split" if apart != plain else None
    return None


def real_template(render, parse, t):
    """A real template's pin, cases, split decision and two-turn renders."""
    t["sha256"] = hashlib.sha256(t["template"].encode("utf-8", "surrogateescape")).hexdigest()
    t["cases"] = render_all(render, t["template"], TEMPLATE_CASES)
    t["split_turns"] = splits_turns(parse, t["template"])
    t["reference_keeps"] = reference_keeps(render, t["template"])
    t["first"] = attempt(render, t["template"], TURN_BEFORE, True)
    turns = []
    for text in TURN_TEXTS:
        kept = m("assistant", *split_turn(text)) if t["split_turns"] else m("assistant", text)
        turns.append(attempt(render, t["template"], TURN_BEFORE + [kept] + TURN_AFTER, True))
    t["turns"] = turns
    return t


def reference():
    """transformers' chat template renderer, which must be the recorded version: `render`, whether a template `compiles`, Jinja's `parse` of one in the renderer's own environment, and the `versions` it reports."""
    from types import SimpleNamespace
    import jinja2
    import transformers
    from transformers.utils.chat_template_utils import _compile_jinja_template, render_jinja_template

    found = {"transformers": transformers.__version__, "jinja2": jinja2.__version__}
    if found != REFERENCE:
        sys.exit("the chat fixtures are rendered with %s; this environment has %s" % (REFERENCE, found))

    def render(template, messages, generate, tools=None):
        return render_jinja_template(conversations=[messages], tools=tools, chat_template=template, add_generation_prompt=generate,
                                     bos_token=BOS, eos_token=EOS)[0][0]

    def compiles(template):
        try:
            _compile_jinja_template(template)
            return True
        except Exception:
            return False

    def parse(template):
        return _compile_jinja_template(template).environment.parse(template)

    versions = {"transformers_version": transformers.__version__, "jinja2_version": jinja2.__version__}
    return SimpleNamespace(render=render, compiles=compiles, parse=parse, versions=versions)


def template_doc(ref, templates):
    """The fixture of the given templates, each {name, origin, template}, with the feature templates, the refusals and the splits."""
    render, compiles = ref.render, ref.compiles
    templates = [real_template(render, ref.parse, t) for t in templates]
    features = [{"name": name, "template": source,
                 "cases": render_all(render, source, [("conversation-%d" % k, c, True) for k, c in enumerate(CONVERSATIONS)])}
                for name, source in FEATURES]
    refused = [{"name": name, "template": source, "why": why, "transformers_compiles": compiles(source)} for name, source, why in REFUSED]
    splits = []
    for text in SPLITS:
        content, reasoning = split_turn(text)
        splits.append({"text": text, "content": content, "reasoning_content": reasoning})
    return dict({"source": "transformers render_jinja_template, the renderer of apply_chat_template", "bos_token": BOS, "eos_token": EOS},
                **ref.versions, turn_before=TURN_BEFORE, turn_after=TURN_AFTER, turn_texts=TURN_TEXTS,
                templates=templates, features=features, refused=refused, splits=splits)


def write(path, doc):
    # Line feeds on every platform, as the committed fixtures hold them.
    path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8", newline="\n")
    print("wrote", path)


def chat_replies(ref):
    """The tiny model's greedy follow-up replies for each case of tests/chat.py."""
    render = ref.render
    import torch
    sys.path.insert(0, str(ROOT / "tests"))
    from chat import CASES
    from f32 import CONFIG, weight_hash
    from gen_baseline import tiny_qwen3

    torch.set_num_threads(1)
    model, weights = tiny_qwen3(False)
    cases = []
    with torch.inference_mode():
        for spec in CASES:
            # chat keeps each reply as chat::ChatFormat::assistant keeps one, and none of these templates splits a turn, so it stays whole.
            assert not splits_turns(ref.parse, spec["template"]), "a chat fixture template that splits turns needs the split here"
            messages = [m("system", "")]
            turns = []
            for text in spec["inputs"]:
                messages.append(m("user", text))
                prompt = list(render(spec["template"], messages, True).encode("latin-1"))
                assert prompt
                reply = []
                for _ in range(spec["max_tokens"]):
                    ids = prompt + reply
                    assert len(ids) < CONFIG["context_length"]
                    logits = model(torch.tensor([ids]), use_cache=False).logits[0, -1]
                    token = int(logits.argmax())
                    if token == spec.get("eos_id", 0):
                        break
                    assert token < 256, "fixture reply must use byte tokens"
                    reply.append(token)
                    if spec.get("stop") and spec["stop"].encode() in bytes(reply):
                        break
                turns.append({"prompt_ids": prompt, "reply_ids": reply})
                messages.append(m("assistant", bytes(reply).decode("latin-1")))
            cases.append({"spec": spec, "turns": turns})
    return dict({"source": "HF Qwen3ForCausalLM, full transcript recomputed each turn, transformers' chat template renderer",
                 "torch_version": torch.__version__}, **ref.versions,
                dtype="float32", attention="eager", config=CONFIG, weights_sha256=weight_hash(weights), cases=cases)


def main():
    parser = argparse.ArgumentParser(description="Regenerate tests/data/baseline_chat.json and baseline_chat_template.json "
                                                 "with transformers' chat template renderer, or scan GGUF files for templates.")
    parser.add_argument("--templates-only", action="store_true", help="regenerate baseline_chat_template.json alone, without torch")
    parser.add_argument("--add", metavar="PATH", help="add the template of a GGUF file, or of a text file, to the pinned templates")
    parser.add_argument("--name", help="the added template's name")
    parser.add_argument("--origin", action="append", default=[], help="where the added template comes from; repeatable")
    parser.add_argument("--extract", nargs="+", metavar="DIR", help="list each distinct template in the GGUF files under DIR instead")
    parser.add_argument("--scan", nargs="+", metavar="LIST", help="render the templates of --extract lists instead")
    parser.add_argument("--out", help="with --extract or --scan, the file to write")
    args = parser.parse_args()
    if (args.extract or args.scan) and not args.out:
        parser.error("--extract and --scan need --out")
    if args.add and not args.name:
        parser.error("--add needs --name")

    if args.extract:
        found, files = {}, 0
        for directory in args.extract:
            for folder, _, names in os.walk(directory, followlinks=True):
                for name in sorted(names):
                    if not name.endswith(".gguf"):
                        continue
                    path = os.path.join(folder, name)
                    try:
                        templates = gguf_templates(path)
                    except (OSError, struct.error) as e:
                        print("skipped %s: %s" % (path, e))
                        continue
                    files += 1
                    source = templates.get("tokenizer.chat_template")
                    if source is None:
                        continue
                    digest = hashlib.sha256(source.encode("utf-8", "surrogateescape")).hexdigest()
                    found.setdefault(digest, {"name": digest[:16], "origin": [], "template": source})["origin"].append(path)
        print("%d GGUF files, %d distinct templates" % (files, len(found)))
        write(Path(args.out), {"gguf_files": files, "templates": list(found.values())})
        return

    # The packages are needed only to render, so --help and --extract run without them.
    ref = reference()
    if args.scan:
        found = {}
        for listing in args.scan:
            for t in json.loads(Path(listing).read_text(encoding="utf-8"))["templates"]:
                found.setdefault(t["name"], {"name": t["name"], "origin": [], "template": t["template"]})["origin"] += t["origin"]
        write(Path(args.out), template_doc(ref, list(found.values())))
        return

    doc = json.loads(TEMPLATES.read_text(encoding="utf-8"))
    templates = []
    for t in doc["templates"]:
        digest = hashlib.sha256(t["template"].encode("utf-8", "surrogateescape")).hexdigest()
        assert digest == t["sha256"], "%s: the committed template no longer matches its pin" % t["name"]
        templates.append({"name": t["name"], "origin": t["origin"], "template": t["template"]})
    if args.add:
        path = Path(args.add)
        with open(path, "rb") as f:
            gguf = f.read(4) == b"GGUF"
        source = gguf_templates(path)["tokenizer.chat_template"] if gguf else path.read_bytes().decode("utf-8", "surrogateescape")
        digest = hashlib.sha256(source.encode("utf-8", "surrogateescape")).hexdigest()
        assert all(hashlib.sha256(t["template"].encode("utf-8", "surrogateescape")).hexdigest() != digest for t in templates), \
            "that template is pinned already"
        templates.append({"name": args.name, "origin": args.origin or [path.name], "template": source})
    write(TEMPLATES, template_doc(ref, templates))
    if not args.templates_only:
        write(CHAT, chat_replies(ref))


if __name__ == "__main__":
    main()
