"""Generate golden fixtures for the correctness baseline.

Run this ONCE on a machine with the HF tooling, then commit the output.
tests/baseline.py only reads the committed JSON, so running the test suite
never needs torch, transformers, or network access -- llmx stays
dependency-free at runtime and the suite stays self-contained.

    python tools/gen_baseline.py

Requires: tokenizers, huggingface_hub (tokenizer goldens) and, for the logit
goldens, torch + transformers. Those two segfault together in some environments
(any `from transformers import Auto*` dies); an isolated venv with numpy<2.3,
torch 2.5.1+cpu and transformers 4.55.2 is known to work.
"""

import io
import json
import os
import sys

TOKENIZER_REPO = "Qwen/Qwen3-0.6B"
GGUF_REPO = "Qwen/Qwen3-0.6B-GGUF"
GGUF_FILE = "Qwen3-0.6B-Q8_0.gguf"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_TOK = os.path.join(ROOT, "tests", "data", "baseline_tokenizer.json")
OUT_LOG = os.path.join(ROOT, "tests", "data", "baseline_logits.json")

# Each case targets a class of pretokenizer behaviour. The multi-space and
# indentation cases are the ones that caught the GPT-2 `\s+(?!\S)` bug, where
# runs of 2+ spaces were emitted whole instead of leaving the last space to
# attach to the following word.
CASES = [
    "hello world",
    "The capital of France is Paris.",
    "  hello",
    "   spaced   out   ",
    "\ttabbed",
    "trailing   ",
    "a\n\nb",
    "don't can't won't",
    "Hello, World! 123 456",
    "3.14159 and 1e-9",
    "cafe naive jalapeno",
    "\u00e9\u00e8\u00ea \u65e5\u672c\u8a9e \u0440\u0443\u0441\u0441\u043a\u0438\u0439",
    "\U0001f600 emoji \U0001f680",
    "def f(x):\n    if x > 0:\n        return x\n    return -x",
    "<|im_start|>user\nhi<|im_end|>",
    "MixedCASE_snake_case-kebab.dot",
]

# Prompts for the logit golden. Plain ASCII and short, so the fixture stays
# small and the comparison is about the forward pass rather than tokenization,
# which the tokenizer golden already covers.
LOGIT_PROMPTS = [
    "The capital of France is",
    "Machine learning is",
    "def add(a, b):",
    "The three primary colors are red,",
    "In 1969, humans first walked on the",
    "The capital of France is Paris. The capital of Italy is Rome. The capital of",
]
TOPN = 10


def gen_tokenizer():
    from tokenizers import Tokenizer
    from huggingface_hub import hf_hub_download
    tok = Tokenizer.from_file(hf_hub_download(TOKENIZER_REPO, "tokenizer.json"))
    cases = [{"text": t, "ids": tok.encode(t, add_special_tokens=False).ids}
             for t in CASES]
    doc = {
        "_comment": "Generated by tools/gen_baseline.py. Do not hand-edit.",
        "tokenizer_repo": TOKENIZER_REPO,
        "gguf_repo": GGUF_REPO,
        "gguf_file": GGUF_FILE,
        "cases": cases,
    }
    _write(OUT_TOK, doc)
    print("wrote %s (%d cases)" % (os.path.relpath(OUT_TOK, ROOT), len(cases)))


def gen_logits():
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    tok = AutoTokenizer.from_pretrained(TOKENIZER_REPO)
    m = AutoModelForCausalLM.from_pretrained(TOKENIZER_REPO, torch_dtype=torch.float32)
    m.eval()
    cases = []
    for p in LOGIT_PROMPTS:
        ids = tok(p, return_tensors="pt").input_ids
        with torch.no_grad():
            lg = m(ids).logits[0, -1].float()
        top = torch.topk(lg, TOPN)
        cases.append({"text": p,
                      "n_tokens": int(ids.shape[1]),
                      "top_ids": top.indices.tolist(),
                      "top_logits": [round(float(v), 4) for v in top.values]})
        print("  %-46s -> %s" % (repr(p)[:46], top.indices.tolist()[:3]))
    doc = {
        "_comment": ("Generated by tools/gen_baseline.py from the FULL-PRECISION "
                     "reference. llmx runs the Q8_0 GGUF, so logits differ by "
                     "quantization error; compare ranks, not values."),
        "reference_repo": TOKENIZER_REPO,
        "reference_dtype": "float32",
        "gguf_repo": GGUF_REPO,
        "gguf_file": GGUF_FILE,
        "topn": TOPN,
        "cases": cases,
    }
    _write(OUT_LOG, doc)
    print("wrote %s (%d prompts)" % (os.path.relpath(OUT_LOG, ROOT), len(cases)))


def _write(path, doc):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")


def main():
    what = sys.argv[1] if len(sys.argv) > 1 else "all"
    if what in ("all", "tokenizer"):
        gen_tokenizer()
    if what in ("all", "logits"):
        gen_logits()


if __name__ == "__main__":
    sys.exit(main())
