"""Generate golden fixtures for the correctness baseline.

Run this ONCE on a machine with the HF tooling, then commit the output.
tests/baseline.py only reads the committed JSON, so running the test suite
never needs torch, transformers, or network access -- llmx stays
dependency-free at runtime and the suite stays self-contained.

    python tools/gen_baseline.py [all|tokenizer|logits|perplexity|f32]

Requires: tokenizers, huggingface_hub (tokenizer goldens) and, for the logit/PPL
goldens, torch + transformers. Those two segfault together in some environments
(any `from transformers import Auto*` dies); an isolated venv with numpy<2.3,
torch 2.5.1+cpu and transformers 4.55.2 is known to work.
"""

import io
import hashlib
import json
import math
import os
import sys

TOKENIZER_REPO = "Qwen/Qwen3-0.6B"
GGUF_REPO = "Qwen/Qwen3-0.6B-GGUF"
GGUF_FILE = "Qwen3-0.6B-Q8_0.gguf"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_TOK = os.path.join(ROOT, "tests", "data", "baseline_tokenizer.json")
OUT_LOG = os.path.join(ROOT, "tests", "data", "baseline_logits.json")
OUT_PPL = os.path.join(ROOT, "tests", "data", "baseline_perplexity.json")
PPL_REVISION = "c1899de289a04d12100db370d81485cdf75e47ca"

# Each case targets a class of pretokenizer behaviour. The multi-space and
# indentation cases are the ones that caught the GPT-2 `\s+(?!\S)` bug, where
# runs of 2+ spaces were emitted whole instead of leaving the last space to
# attach to the following word.
CASES = [
    "hello world",
    "The capital of France is Paris.",
    "  hello",
    "   spaced   out   ",
    "\ttabbed",
    "trailing   ",
    "a\n\nb",
    "don't can't won't",
    "Hello, World! 123 456",
    "3.14159 and 1e-9",
    "cafe naive jalapeno",
    "\u00e9\u00e8\u00ea \u65e5\u672c\u8a9e \u0440\u0443\u0441\u0441\u043a\u0438\u0439",
    "\U0001f600 emoji \U0001f680",
    "def f(x):\n    if x > 0:\n        return x\n    return -x",
    "<|im_start|>user\nhi<|im_end|>",
    "MixedCASE_snake_case-kebab.dot",
    "\u00ad",
    "co\u00adoperate",
    "\u4e2d\u6587",
    "\u036d",
]

# Prompts for the logit golden. Plain ASCII and short, so the fixture stays
# small and the comparison is about the forward pass rather than tokenization,
# which the tokenizer golden already covers.
LOGIT_PROMPTS = [
    "The capital of France is",
    "Machine learning is",
    "def add(a, b):",
    "The three primary colors are red,",
    "In 1969, humans first walked on the",
    "The capital of France is Paris. The capital of Italy is Rome. The capital of",
]
TOPN = 10


def gen_tokenizer():
    from tokenizers import Tokenizer
    from huggingface_hub import hf_hub_download
    tok = Tokenizer.from_file(hf_hub_download(TOKENIZER_REPO, "tokenizer.json", revision=PPL_REVISION))
    cases = [{"text": t, "ids": tok.encode(t, add_special_tokens=False).ids}
             for t in CASES]
    doc = {
        "_comment": "Generated by tools/gen_baseline.py. Do not hand-edit.",
        "tokenizer_repo": TOKENIZER_REPO,
        "tokenizer_revision": PPL_REVISION,
        "gguf_repo": GGUF_REPO,
        "gguf_file": GGUF_FILE,
        "cases": cases,
    }
    _write(OUT_TOK, doc)
    print("wrote %s (%d cases)" % (os.path.relpath(OUT_TOK, ROOT), len(cases)))


def gen_logits():
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    tok = AutoTokenizer.from_pretrained(TOKENIZER_REPO)
    m = AutoModelForCausalLM.from_pretrained(TOKENIZER_REPO, torch_dtype=torch.float32)
    m.eval()
    cases = []
    for p in LOGIT_PROMPTS:
        ids = tok(p, return_tensors="pt").input_ids
        with torch.no_grad():
            lg = m(ids).logits[0, -1].float()
        top = torch.topk(lg, TOPN)
        cases.append({"text": p,
                      "n_tokens": int(ids.shape[1]),
                      "top_ids": top.indices.tolist(),
                      "top_logits": [round(float(v), 4) for v in top.values]})
        print("  %-46s -> %s" % (repr(p)[:46], top.indices.tolist()[:3]))
    doc = {
        "_comment": ("Generated by tools/gen_baseline.py from the FULL-PRECISION "
                     "reference. llmx runs the Q8_0 GGUF, so logits differ by "
                     "quantization error; compare ranks, not values."),
        "reference_repo": TOKENIZER_REPO,
        "reference_dtype": "float32",
        "gguf_repo": GGUF_REPO,
        "gguf_file": GGUF_FILE,
        "topn": TOPN,
        "cases": cases,
    }
    _write(OUT_LOG, doc)
    print("wrote %s (%d prompts)" % (os.path.relpath(OUT_LOG, ROOT), len(cases)))


def gen_perplexity():
    import torch
    import transformers
    from transformers import AutoModelForCausalLM, AutoTokenizer

    torch.set_num_threads(6)
    with open(os.path.join(ROOT, "tests", "data", "wiki.test.raw"), encoding="utf-8") as f:
        text = f.read(1024)
    tok = AutoTokenizer.from_pretrained(TOKENIZER_REPO, revision=PPL_REVISION)
    model = AutoModelForCausalLM.from_pretrained(
        TOKENIZER_REPO, revision=PPL_REVISION, torch_dtype=torch.float32,
        attn_implementation="eager")
    model.eval()
    ids = tok(text, add_special_tokens=False, return_tensors="pt").input_ids
    with torch.inference_mode():
        logits = model(ids, use_cache=False).logits[0, :-1].double()
        targets = ids[0, 1:]
        nll = torch.logsumexp(logits, dim=-1) - logits.gather(1, targets[:, None]).squeeze(1)
        mean_nll = nll.mean().item()
    chunk_cases = []
    for context, limit in ((64, 0), (64, 2), (123, 0)):
        total_nll, used, scored, chunks = 0.0, 0, 0, 0
        for window in ids.split(context, dim=1):
            count = window.shape[1]
            if count < 2 or (limit and chunks >= limit):
                break
            with torch.inference_mode():
                logits = model(window, use_cache=False).logits[0, :-1].double()
                targets = window[0, 1:]
                loss = torch.logsumexp(logits, dim=-1) - logits.gather(1, targets[:, None]).squeeze(1)
            total_nll += loss.sum().item()
            used += count
            scored += count - 1
            chunks += 1
        chunk_cases.append({"context_size": context, "max_chunks": limit,
                            "used_tokens": used, "n_scored": scored, "chunks": chunks,
                            "mean_nll": total_nll / scored,
                            "perplexity": math.exp(total_nll / scored)})
    doc = {
        "_comment": "Generated by tools/gen_baseline.py perplexity. Do not hand-edit.",
        "reference_repo": TOKENIZER_REPO,
        "reference_revision": PPL_REVISION,
        "reference_dtype": "float32",
        "attention": "eager",
        "torch_version": torch.__version__,
        "transformers_version": transformers.__version__,
        "source": "wiki.test.raw, first 1024 Unicode characters after CRLF/CR normalization to LF",
        "scoring": "One continuous sequence, no BOS/EOS added; score tokens 1..N-1 from preceding tokens; float64 log-softmax/reduction of fp32 logits.",
        "text": text,
        "text_sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
        "token_ids": ids[0].tolist(),
        "n_tokens": ids.shape[1],
        "n_scored": ids.shape[1] - 1,
        "mean_nll": mean_nll,
        "perplexity": math.exp(mean_nll),
        "chunk_scoring": "Tokenize once; disjoint windows with reset positions/KV; score tokens 1..L-1 per window; include partial windows of >=2 tokens; omit singleton tail; aggregate total NLL / total targets.",
        "chunk_cases": chunk_cases,
    }
    _write(OUT_PPL, doc)
    print("wrote %s (%d tokens, mean NLL %.9f, PPL %.9f)"
          % (os.path.relpath(OUT_PPL, ROOT), doc["n_tokens"], mean_nll, doc["perplexity"]))


def _write(path, doc):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")


def gen_f32():
    import torch
    import transformers
    from transformers import Qwen3Config, Qwen3ForCausalLM
    sys.path.insert(0, os.path.join(ROOT, "tests"))
    from f32 import CONFIG, TEXTS, tensors, weight_hash

    torch.set_num_threads(1)
    fixtures = []
    for tied in (False, True):
        config = Qwen3Config(vocab_size=257, hidden_size=37, intermediate_size=19,
                             num_hidden_layers=2, num_attention_heads=2, num_key_value_heads=1,
                             head_dim=10, max_position_embeddings=16, rope_theta=10000.0,
                             rms_norm_eps=1e-6, tie_word_embeddings=tied, attention_dropout=0.0)
        config._attn_implementation = "eager"
        model = Qwen3ForCausalLM(config).float().eval()
        weights = tensors(tied)
        state = {name: torch.tensor(values, dtype=torch.float32).reshape(list(reversed(shape)))
                 for _, name, shape, values in weights}
        if tied:
            state["lm_head.weight"] = state["model.embed_tokens.weight"]
        model.load_state_dict(state, strict=True)
        cases, perplexity = [], []
        with torch.inference_mode():
            for text in TEXTS:
                ids = torch.tensor([list(text.encode("ascii"))])
                logits = model(ids, use_cache=False).logits[0, -1]
                cases.append({"text": text, "logits": logits.tolist()})
            ids = torch.tensor([list(TEXTS[-1].encode("ascii"))])
            for context in (4, 16):
                total, targets = 0.0, 0
                for window in ids.split(context, dim=1):
                    if window.shape[1] < 2:
                        continue
                    logits = model(window, use_cache=False).logits[0, :-1].double()
                    loss = torch.logsumexp(logits, -1) - logits.gather(1, window[0, 1:, None]).squeeze(1)
                    total += loss.sum().item()
                    targets += loss.numel()
                perplexity.append({"context": context, "mean_nll": total / targets})
        fixtures.append({"tied": tied, "weights_sha256": weight_hash(weights),
                         "cases": cases, "perplexity": perplexity})
    _write(os.path.join(ROOT, "tests", "data", "baseline_f32.json"), {
        "_comment": "Generated by tools/gen_baseline.py f32 using HF Qwen3ForCausalLM with deterministic synthetic weights.",
        "torch_version": torch.__version__, "transformers_version": transformers.__version__,
        "dtype": "float32", "attention": "eager", "config": CONFIG, "fixtures": fixtures})
    print("wrote tests/data/baseline_f32.json (tied/untied, full logits and windowed NLL)")


def main():
    what = sys.argv[1] if len(sys.argv) > 1 else "all"
    if what in ("all", "tokenizer"):
        gen_tokenizer()
    if what in ("all", "logits"):
        gen_logits()
    if what in ("all", "perplexity"):
        gen_perplexity()
    if what in ("all", "f32"):
        gen_f32()


if __name__ == "__main__":
    sys.exit(main())
