set(revision "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" rev-parse --show-toplevel
        OUTPUT_VARIABLE git_root OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    get_filename_component(source_root "${SOURCE_ROOT}" REALPATH)
    get_filename_component(git_root "${git_root}" REALPATH)
    if(WIN32)
        string(TOLOWER "${source_root}" source_root)
        string(TOLOWER "${git_root}" git_root)
    endif()
    if(git_root STREQUAL source_root)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" rev-parse --short=12 HEAD
            OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
            RESULT_VARIABLE commit_result)
        if(commit_result EQUAL 0 AND commit MATCHES "^[0-9a-f]+$")
            execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" diff --quiet HEAD --
                RESULT_VARIABLE dirty ERROR_QUIET)
            if(dirty EQUAL 0)
                set(revision "g${commit}")
            elseif(dirty EQUAL 1)
                set(revision "g${commit}.dirty")
            endif()
        endif()
    endif()
endif()

set(content "#pragma once\n#define LLMX_BUILD_REVISION \"${revision}\"\n")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT_FILE}" "${content}")
