set(revision "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" rev-parse --show-toplevel
        OUTPUT_VARIABLE git_root OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    get_filename_component(source_root "${SOURCE_ROOT}" REALPATH)
    get_filename_component(git_root "${git_root}" REALPATH)
    if(WIN32)
        string(TOLOWER "${source_root}" source_root)
        string(TOLOWER "${git_root}" git_root)
    endif()
    if(git_root STREQUAL source_root)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" rev-parse --short=12 HEAD
            OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
            RESULT_VARIABLE commit_result)
        if(commit_result EQUAL 0 AND commit MATCHES "^[0-9a-f]+$")
            execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_ROOT}" diff --quiet HEAD --
                RESULT_VARIABLE dirty ERROR_QUIET)
            if(dirty EQUAL 0)
                set(revision "g${commit}")
            elseif(dirty EQUAL 1)
                set(revision "g${commit}.dirty")
            endif()
        endif()
    endif()
endif()

# The numerics fingerprint (cmake/numerics-sources.txt, docs/DISK-TIER.md, The entry file): each file in, in path order, as "path sha256\n" with CRLF read as LF, and the SHA-256 of those lines.
# cmake/numerics-fingerprint.ps1 and tests/version.py compute the same value.
file(STRINGS "${SOURCE_ROOT}/cmake/numerics-sources.txt" lines)
set(ins)
set(outs)
foreach(line IN LISTS lines)
    if(line MATCHES "^in +([^ |]+)")
        list(APPEND ins "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^out +([^ |]+)")
        list(APPEND outs "${CMAKE_MATCH_1}")
    endif()
endforeach()
set(files)
foreach(in IN LISTS ins)
    if(IS_DIRECTORY "${SOURCE_ROOT}/${in}")
        file(GLOB_RECURSE found RELATIVE "${SOURCE_ROOT}" "${SOURCE_ROOT}/${in}/*")
        list(APPEND files ${found})
    else()
        list(APPEND files "${in}")
    endif()
endforeach()
set(kept)
foreach(file IN LISTS files)
    set(skip FALSE)
    foreach(out IN LISTS outs)
        string(LENGTH "${out}/" n)
        string(SUBSTRING "${file}" 0 ${n} head)
        if(file STREQUAL out OR head STREQUAL "${out}/")
            set(skip TRUE)
        endif()
    endforeach()
    if(NOT skip)
        list(APPEND kept "${file}")
    endif()
endforeach()
list(SORT kept)
set(text "")
foreach(file IN LISTS kept)
    file(READ "${SOURCE_ROOT}/${file}" bytes HEX)
    string(REPLACE "0d0a" "0a" folded "${bytes}")
    string(SHA256 hash "${folded}")
    string(APPEND text "${file} ${hash}\n")
endforeach()
string(SHA256 numerics "${text}")

# What was compiled beyond the sources: the compiler, the configuration's flags and the build options, which no file holds, and the shader compiler.
string(TOUPPER "${BUILD_CONFIG}" config)
set(flags "${COMPILER}; ${BUILD_CONFIG}; ${CXX_FLAGS} ${CXX_FLAGS_${config}}; vulkan ${VULKAN}; ipo ${IPO}")
string(REPLACE "\\" "\\\\" flags "${flags}")
string(REPLACE "\"" "\\\"" flags "${flags}")
string(REPLACE "\\" "\\\\" glslc "${GLSLC_VERSION}")
string(REPLACE "\"" "\\\"" glslc "${glslc}")

set(content "#pragma once\n#define LLMX_BUILD_REVISION \"${revision}\"\n#define LLMX_NUMERICS \"${numerics}\"\n#define LLMX_BUILD_FLAGS \"${flags}\"\n#define LLMX_GLSLC_VERSION \"${glslc}\"\n")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT_FILE}" "${content}")
